export const STOCKS = [
  // ================= ENERGY =================
  { symbol: "RELIANCE.NS", sectorId: 7, sector: "Energy", category: "Nifty50", displayName: "Reliance Industries Ltd", stockNameCategory: "Largecap" },
  { symbol: "ONGC.NS", sectorId: 7, sector: "Energy", category: "Nifty50", displayName: "Oil and Natural Gas Corporation Ltd", stockNameCategory: "Largecap" },
  { symbol: "IOC.NS", sectorId: 7, sector: "Energy", category: "Midcap", displayName: "Indian Oil Corporation Ltd", stockNameCategory: "Largecap" },
  { symbol: "BPCL.NS", sectorId: 7, sector: "Energy", category: "Midcap", displayName: "Bharat Petroleum Corporation Ltd", stockNameCategory: "Largecap" },
  { symbol: "HINDPETRO.NS", sectorId: 7, sector: "Energy", category: "Midcap", displayName: "Hindustan Petroleum Corporation Ltd", stockNameCategory: "Largecap" },
  { symbol: "GAIL.NS", sectorId: 7, sector: "Energy", category: "Midcap", displayName: "GAIL (India) Ltd", stockNameCategory: "Largecap" },
  { symbol: "OIL.NS", sectorId: 7, sector: "Energy", category: "Midcap", displayName: "Oil India Ltd", stockNameCategory: "Midcap" },
  { symbol: "PETRONET.NS", sectorId: 7, sector: "Energy", category: "Midcap", displayName: "Petronet LNG Ltd", stockNameCategory: "Midcap" },
  { symbol: "IGL.NS", sectorId: 7, sector: "Energy", category: "Midcap", displayName: "Indraprastha Gas Ltd", stockNameCategory: "Midcap" },
  { symbol: "MGL.NS", sectorId: 7, sector: "Energy", category: "Midcap", displayName: "Mahanagar Gas Ltd", stockNameCategory: "Midcap" },
  { symbol: "GSPL.NS", sectorId: 7, sector: "Energy", category: "Midcap", displayName: "Gujarat State Petronet Ltd", stockNameCategory: "Midcap" },
  { symbol: "GUJGASLTD.NS", sectorId: 7, sector: "Energy", category: "Midcap", displayName: "Gujarat Gas Ltd", stockNameCategory: "Midcap" },
  { symbol: "ATGL.NS", sectorId: 7, sector: "Energy", category: "Midcap", displayName: "Adani Total Gas Ltd", stockNameCategory: "Midcap" },
  { symbol: "ADANIGREEN.NS", sectorId: 7, sector: "Energy", category: "Midcap", displayName: "Adani Green Energy Ltd", stockNameCategory: "Largecap" },
  { symbol: "ADANIPOWER.NS", sectorId: 7, sector: "Energy", category: "Midcap", displayName: "Adani Power Ltd", stockNameCategory: "Largecap" },
  { symbol: "NTPC.NS", sectorId: 7, sector: "Energy", category: "Nifty50", displayName: "NTPC Ltd", stockNameCategory: "Largecap" },
  { symbol: "NHPC.NS", sectorId: 7, sector: "Energy", category: "Midcap", displayName: "NHPC Ltd", stockNameCategory: "Midcap" },
  { symbol: "SJVN.NS", sectorId: 7, sector: "Energy", category: "Midcap", displayName: "SJVN Ltd", stockNameCategory: "Midcap" },
  { symbol: "TORNTPOWER.NS", sectorId: 7, sector: "Energy", category: "Midcap", displayName: "Torrent Power Ltd", stockNameCategory: "Midcap" },
  { symbol: "TATAPOWER.NS", sectorId: 7, sector: "Energy", category: "Midcap", displayName: "Tata Power Company Ltd", stockNameCategory: "Largecap" },
  { symbol: "JSWENERGY.NS", sectorId: 7, sector: "Energy", category: "Midcap", displayName: "JSW Energy Ltd", stockNameCategory: "Midcap" },
  { symbol: "CESC.NS", sectorId: 7, sector: "Energy", category: "Midcap", displayName: "CESC Ltd", stockNameCategory: "Midcap" },
  { symbol: "NLCINDIA.NS", sectorId: 7, sector: "Energy", category: "Midcap", displayName: "NLC India Ltd", stockNameCategory: "Midcap" },
  { symbol: "POWERGRID.NS", sectorId: 7, sector: "Energy", category: "Nifty50", displayName: "Power Grid Corporation of India Ltd", stockNameCategory: "Largecap" },
  { symbol: "ADANIENSOL.NS", sectorId: 7, sector: "Energy", category: "Midcap", displayName: "Adani Energy Solutions Ltd", stockNameCategory: "Midcap" },
  // ================= MATERIALS =================
  { symbol: "ULTRACEMCO.NS", sectorId: 8, sector: "Materials", category: "Midcap", displayName: "UltraTech Cement Ltd", stockNameCategory: "Largecap" },
  { symbol: "GRASIM.NS", sectorId: 8, sector: "Materials", category: "Midcap", displayName: "Grasim Industries Ltd", stockNameCategory: "Largecap" },
  { symbol: "TATASTEEL.NS", sectorId: 8, sector: "Materials", category: "Nifty50", displayName: "Tata Steel Ltd", stockNameCategory: "Largecap" },
  { symbol: "JSWSTEEL.NS", sectorId: 8, sector: "Materials", category: "Midcap", displayName: "JSW Steel Ltd", stockNameCategory: "Largecap" },
  { symbol: "HINDALCO.NS", sectorId: 8, sector: "Materials", category: "Nifty50", displayName: "Hindalco Industries Ltd", stockNameCategory: "Largecap" },
  { symbol: "VEDL.NS", sectorId: 8, sector: "Materials", category: "Midcap", displayName: "Vedanta Ltd", stockNameCategory: "Largecap" },
  { symbol: "SAIL.NS", sectorId: 8, sector: "Materials", category: "Midcap", displayName: "Steel Authority of India Ltd", stockNameCategory: "Midcap" },
  { symbol: "JINDALSTEL.NS", sectorId: 8, sector: "Materials", category: "Midcap", displayName: "Jindal Steel & Power Ltd", stockNameCategory: "Midcap" },
  { symbol: "NMDC.NS", sectorId: 8, sector: "Materials", category: "Midcap", displayName: "NMDC Ltd", stockNameCategory: "Midcap" },
  { symbol: "AMBUJACEM.NS", sectorId: 8, sector: "Materials", category: "Midcap", displayName: "Ambuja Cements Ltd", stockNameCategory: "Largecap" },
  { symbol: "ACC.NS", sectorId: 8, sector: "Materials", category: "Midcap", displayName: "ACC Ltd", stockNameCategory: "Midcap" },
  { symbol: "DALBHARAT.NS", sectorId: 8, sector: "Materials", category: "Midcap", displayName: "Dalmia Bharat Ltd", stockNameCategory: "Midcap" },
  { symbol: "RAMCOCEM.NS", sectorId: 8, sector: "Materials", category: "Midcap", displayName: "The Ramco Cements Ltd", stockNameCategory: "Midcap" },
  { symbol: "APLAPOLLO.NS", sectorId: 8, sector: "Materials", category: "Midcap", displayName: "Apollo Pipes Ltd", stockNameCategory: "Midcap" },
  { symbol: "JSPL.NS", sectorId: 8, sector: "Materials", category: "Midcap", displayName: "Jindal Steel & Power Ltd", stockNameCategory: "Midcap" },
  { symbol: "HINDZINC.NS", sectorId: 8, sector: "Materials", category: "Midcap", displayName: "Hindustan Zinc Ltd", stockNameCategory: "Largecap" },
  { symbol: "NATIONALUM.NS", sectorId: 8, sector: "Materials", category: "Midcap", displayName: "National Aluminium Company Ltd", stockNameCategory: "Midcap" },
  { symbol: "MOIL.NS", sectorId: 8, sector: "Materials", category: "Midcap", displayName: "MOIL Ltd", stockNameCategory: "Midcap" },
  { symbol: "RATNAMANI.NS", sectorId: 8, sector: "Materials", category: "Midcap", displayName: "Ratnamani Metals & Tubes Ltd", stockNameCategory: "Midcap" },
  { symbol: "SUPREMEIND.NS", sectorId: 8, sector: "Materials", category: "Midcap", displayName: "Supreme Industries Ltd", stockNameCategory: "Midcap" },
  { symbol: "ASTRAL.NS", sectorId: 8, sector: "Materials", category: "Midcap", displayName: "Astral Ltd", stockNameCategory: "Midcap" },
  { symbol: "KANSAINER.NS", sectorId: 8, sector: "Materials", category: "Midcap", displayName: "Kansai Nerolac Paints Ltd", stockNameCategory: "Midcap" },
  { symbol: "BERGEPAINT.NS", sectorId: 8, sector: "Materials", category: "Midcap", displayName: "Berger Paints India Ltd", stockNameCategory: "Midcap" },
  { symbol: "PIDILITIND.NS", sectorId: 8, sector: "Materials", category: "Midcap", displayName: "Pidilite Industries Ltd", stockNameCategory: "Largecap" },
  { symbol: "DEEPAKNTR.NS", sectorId: 8, sector: "Materials", category: "Midcap", displayName: "Deepak Nitrite Ltd", stockNameCategory: "Midcap" },
  // ================= FINANCIALS =================
  { symbol: "HDFCBANK.NS", sectorId: 2, sector: "Financials", category: "Nifty50", displayName: "HDFC Bank Ltd", stockNameCategory: "Largecap" },
  { symbol: "ICICIBANK.NS", sectorId: 2, sector: "Financials", category: "Nifty50", displayName: "ICICI Bank Ltd", stockNameCategory: "Largecap" },
  { symbol: "SBIN.NS", sectorId: 2, sector: "Financials", category: "Nifty50", displayName: "State Bank of India", stockNameCategory: "Largecap" },
  { symbol: "KOTAKBANK.NS", sectorId: 2, sector: "Financials", category: "Nifty50", displayName: "Kotak Mahindra Bank Ltd", stockNameCategory: "Largecap" },
  { symbol: "AXISBANK.NS", sectorId: 2, sector: "Financials", category: "Nifty50", displayName: "Axis Bank Ltd", stockNameCategory: "Largecap" },
  { symbol: "BAJFINANCE.NS", sectorId: 2, sector: "Financials", category: "Nifty50", displayName: "Bajaj Finance Ltd", stockNameCategory: "Largecap" },
  { symbol: "BAJAJFINSV.NS", sectorId: 2, sector: "Financials", category: "Nifty50", displayName: "Bajaj Finserv Ltd", stockNameCategory: "Largecap" },
  { symbol: "HDFCLIFE.NS", sectorId: 2, sector: "Financials", category: "Midcap", displayName: "HDFC Life Insurance Company Ltd", stockNameCategory: "Largecap" },
  { symbol: "SBILIFE.NS", sectorId: 2, sector: "Financials", category: "Midcap", displayName: "SBI Life Insurance Company Ltd", stockNameCategory: "Largecap" },
  { symbol: "ICICIPRULI.NS", sectorId: 2, sector: "Financials", category: "Midcap", displayName: "ICICI Prudential Life Insurance Company Ltd", stockNameCategory: "Largecap" },
  { symbol: "ICICIGI.NS", sectorId: 2, sector: "Financials", category: "Midcap", displayName: "ICICI Lombard General Insurance Company Ltd", stockNameCategory: "Midcap" },
  { symbol: "PFC.NS", sectorId: 2, sector: "Financials", category: "Midcap", displayName: "Power Finance Corporation Ltd", stockNameCategory: "Largecap" },
  { symbol: "RECLTD.NS", sectorId: 2, sector: "Financials", category: "Midcap", displayName: "REC Ltd", stockNameCategory: "Largecap" },
  { symbol: "CHOLAFIN.NS", sectorId: 2, sector: "Financials", category: "Midcap", displayName: "Cholamandalam Investment and Finance Company Ltd", stockNameCategory: "Midcap" },
  { symbol: "MUTHOOTFIN.NS", sectorId: 2, sector: "Financials", category: "Midcap", displayName: "Muthoot Finance Ltd", stockNameCategory: "Midcap" },
  { symbol: "LICI.NS", sectorId: 2, sector: "Financials", category: "Midcap", displayName: "Life Insurance Corporation of India", stockNameCategory: "Largecap" },
  { symbol: "HDFCAMC.NS", sectorId: 2, sector: "Financials", category: "Midcap", displayName: "HDFC Asset Management Company Ltd", stockNameCategory: "Midcap" },
  { symbol: "IDFCFIRSTB.NS", sectorId: 2, sector: "Financials", category: "Midcap", displayName: "IDFC First Bank Ltd", stockNameCategory: "Midcap" },
  { symbol: "FEDERALBNK.NS", sectorId: 2, sector: "Financials", category: "Midcap", displayName: "Federal Bank Ltd", stockNameCategory: "Midcap" },
  { symbol: "BANDHANBNK.NS", sectorId: 2, sector: "Financials", category: "Midcap", displayName: "Bandhan Bank Ltd", stockNameCategory: "Midcap" },
  { symbol: "INDUSINDBK.NS", sectorId: 2, sector: "Financials", category: "Midcap", displayName: "IndusInd Bank Ltd", stockNameCategory: "Largecap" },
  { symbol: "CANBK.NS", sectorId: 2, sector: "Financials", category: "Midcap", displayName: "Canara Bank", stockNameCategory: "Midcap" },
  { symbol: "BANKBARODA.NS", sectorId: 2, sector: "Financials", category: "Midcap", displayName: "Bank of Baroda", stockNameCategory: "Largecap" },
  { symbol: "UNIONBANK.NS", sectorId: 2, sector: "Financials", category: "Midcap", displayName: "Union Bank of India", stockNameCategory: "Midcap" },
  { symbol: "AUBANK.NS", sectorId: 2, sector: "Financials", category: "Midcap", displayName: "AU Small Finance Bank Ltd", stockNameCategory: "Midcap" },
  // ================= IT =================
  { symbol: "TCS.NS", sectorId: 1, sector: "Information Technology", category: "Nifty50", displayName: "Tata Consultancy Services Ltd", stockNameCategory: "Largecap" },
  { symbol: "INFY.NS", sectorId: 1, sector: "Information Technology", category: "Nifty50", displayName: "Infosys Ltd", stockNameCategory: "Largecap" },
  { symbol: "HCLTECH.NS", sectorId: 1, sector: "Information Technology", category: "Nifty50", displayName: "HCL Technologies Ltd", stockNameCategory: "Largecap" },
  { symbol: "WIPRO.NS", sectorId: 1, sector: "Information Technology", category: "Nifty50", displayName: "Wipro Ltd", stockNameCategory: "Largecap" },
  { symbol: "LTIM.NS", sectorId: 1, sector: "Information Technology", category: "Midcap", displayName: "LTIMindtree Ltd", stockNameCategory: "Largecap" },
  { symbol: "TECHM.NS", sectorId: 1, sector: "Information Technology", category: "Midcap", displayName: "Tech Mahindra Ltd", stockNameCategory: "Largecap" },
  { symbol: "PERSISTENT.NS", sectorId: 1, sector: "Information Technology", category: "Midcap", displayName: "Persistent Systems Ltd", stockNameCategory: "Midcap" },
  { symbol: "MPHASIS.NS", sectorId: 1, sector: "Information Technology", category: "Midcap", displayName: "Mphasis Ltd", stockNameCategory: "Midcap" },
  { symbol: "COFORGE.NS", sectorId: 1, sector: "Information Technology", category: "Midcap", displayName: "Coforge Ltd", stockNameCategory: "Midcap" },
  { symbol: "LTTS.NS", sectorId: 1, sector: "Information Technology", category: "Midcap", displayName: "L&T Technology Services Ltd", stockNameCategory: "Midcap" },
  { symbol: "TATAELXSI.NS", sectorId: 1, sector: "Information Technology", category: "Midcap", displayName: "Tata Elxsi Ltd", stockNameCategory: "Midcap" },
  { symbol: "KPITTECH.NS", sectorId: 1, sector: "Information Technology", category: "Midcap", displayName: "KPIT Technologies Ltd", stockNameCategory: "Midcap" },
  { symbol: "SONATSOFTW.NS", sectorId: 1, sector: "Information Technology", category: "Midcap", displayName: "Sonata Software Ltd", stockNameCategory: "Midcap" },
  { symbol: "ZENSARTECH.NS", sectorId: 1, sector: "Information Technology", category: "Midcap", displayName: "Zensar Technologies Ltd", stockNameCategory: "Midcap" },
  { symbol: "CYIENT.NS", sectorId: 1, sector: "Information Technology", category: "Midcap", displayName: "Cyient Ltd", stockNameCategory: "Midcap" },
  { symbol: "BIRLASOFT.NS", sectorId: 1, sector: "Information Technology", category: "Midcap", displayName: "Birlasoft Ltd", stockNameCategory: "Midcap" },
  { symbol: "HAPPSTMNDS.NS", sectorId: 1, sector: "Information Technology", category: "Midcap", displayName: "Happiest Minds Technologies Ltd", stockNameCategory: "Midcap" },
  { symbol: "NEWGEN.NS", sectorId: 1, sector: "Information Technology", category: "Midcap", displayName: "Newgen Software Technologies Ltd", stockNameCategory: "Midcap" },
  { symbol: "RAMCOSYS.NS", sectorId: 1, sector: "Information Technology", category: "Midcap", displayName: "Ramco Systems Ltd", stockNameCategory: "Smallcap" },
  { symbol: "OFSS.NS", sectorId: 1, sector: "Information Technology", category: "Midcap", displayName: "Oracle Financial Services Software Ltd", stockNameCategory: "Midcap" },
  { symbol: "INTELLECT.NS", sectorId: 1, sector: "Information Technology", category: "Midcap", displayName: "Intellect Design Arena Ltd", stockNameCategory: "Midcap" },
  { symbol: "ROUTE.NS", sectorId: 1, sector: "Information Technology", category: "Midcap", displayName: "Route Mobile Ltd", stockNameCategory: "Midcap" },
  { symbol: "LATENTVIEW.NS", sectorId: 1, sector: "Information Technology", category: "Midcap", displayName: "Latent View Analytics Ltd", stockNameCategory: "Midcap" },
  { symbol: "TANLA.NS", sectorId: 1, sector: "Information Technology", category: "Midcap", displayName: "Tanla Platforms Ltd", stockNameCategory: "Midcap" },
  { symbol: "AFFLE.NS", sectorId: 1, sector: "Information Technology", category: "Midcap", displayName: "Affle (India) Ltd", stockNameCategory: "Midcap" },
  // ================= REAL ESTATE =================
  { symbol: "DLF.NS", sectorId: 10, sector: "Real Estate", category: "Midcap", displayName: "DLF Ltd", stockNameCategory: "Largecap" },
  { symbol: "GODREJPROP.NS", sectorId: 10, sector: "Real Estate", category: "Midcap", displayName: "Godrej Properties Ltd", stockNameCategory: "Midcap" },
  { symbol: "OBEROIRLTY.NS", sectorId: 10, sector: "Real Estate", category: "Midcap", displayName: "Oberoi Realty Ltd", stockNameCategory: "Midcap" },
  { symbol: "PHOENIXLTD.NS", sectorId: 10, sector: "Real Estate", category: "Midcap", displayName: "Phoenix Mills Ltd", stockNameCategory: "Midcap" },
  { symbol: "BRIGADE.NS", sectorId: 10, sector: "Real Estate", category: "Midcap", displayName: "Brigade Enterprises Ltd", stockNameCategory: "Midcap" },
  { symbol: "SOBHA.NS", sectorId: 10, sector: "Real Estate", category: "Midcap", displayName: "Sobha Ltd", stockNameCategory: "Midcap" },
  { symbol: "PRESTIGE.NS", sectorId: 10, sector: "Real Estate", category: "Midcap", displayName: "Prestige Estates Projects Ltd", stockNameCategory: "Midcap" },
  { symbol: "LODHA.NS", sectorId: 10, sector: "Real Estate", category: "Midcap", displayName: "Macrotech Developers Ltd", stockNameCategory: "Largecap" },
  { symbol: "MAHLIFE.NS", sectorId: 10, sector: "Real Estate", category: "Midcap", displayName: "Mahindra Lifespace Developers Ltd", stockNameCategory: "Midcap" },
  { symbol: "SUNTECK.NS", sectorId: 10, sector: "Real Estate", category: "Midcap", displayName: "Sunteck Realty Ltd", stockNameCategory: "Midcap" },
  { symbol: "KOLTEPATIL.NS", sectorId: 10, sector: "Real Estate", category: "Midcap", displayName: "Kolte-Patil Developers Ltd", stockNameCategory: "Midcap" },
  { symbol: "PURVA.NS", sectorId: 10, sector: "Real Estate", category: "Midcap", displayName: "Puravankara Ltd", stockNameCategory: "Smallcap" },
  { symbol: "ANANTRAJ.NS", sectorId: 10, sector: "Real Estate", category: "Midcap", displayName: "Anant Raj Ltd", stockNameCategory: "Midcap" },
  { symbol: "IBREALEST.NS", sectorId: 10, sector: "Real Estate", category: "Midcap", displayName: "Indiabulls Real Estate Ltd", stockNameCategory: "Smallcap" },
  { symbol: "HEMIPROP.NS", sectorId: 10, sector: "Real Estate", category: "Smallcap", displayName: "Hemisphere Properties India Ltd", stockNameCategory: "Smallcap" },
  { symbol: "ASHIANA.NS", sectorId: 10, sector: "Real Estate", category: "Midcap", displayName: "Ashiana Housing Ltd", stockNameCategory: "Smallcap" },
  { symbol: "DBREALTY.NS", sectorId: 10, sector: "Real Estate", category: "Smallcap", displayName: "D B Realty Ltd", stockNameCategory: "Smallcap" },
  { symbol: "OMAXE.NS", sectorId: 10, sector: "Real Estate", category: "Smallcap", displayName: "Omaxe Ltd", stockNameCategory: "Smallcap" },
  { symbol: "UNITECH.NS", sectorId: 10, sector: "Real Estate", category: "Smallcap", displayName: "Unitech Ltd", stockNameCategory: "Penny" },
  { symbol: "VIPULLTD.NS", sectorId: 10, sector: "Real Estate", category: "Smallcap", displayName: "Vipul Ltd", stockNameCategory: "Penny" },
  { symbol: "ARVSMART.NS", sectorId: 10, sector: "Real Estate", category: "Smallcap", displayName: "Arvind SmartSpaces Ltd", stockNameCategory: "Smallcap" },
  { symbol: "NILKAMAL.NS", sectorId: 10, sector: "Real Estate", category: "Midcap", displayName: "Nilkamal Ltd", stockNameCategory: "Midcap" },
  { symbol: "PSPPROJECT.NS", sectorId: 10, sector: "Real Estate", category: "Midcap", displayName: "PSP Projects Ltd", stockNameCategory: "Smallcap" },
  { symbol: "CAPACITE.NS", sectorId: 10, sector: "Real Estate", category: "Midcap", displayName: "Capacite Infraprojects Ltd", stockNameCategory: "Smallcap" },
  { symbol: "AHLEAST.NS", sectorId: 10, sector: "Real Estate", category: "Smallcap", displayName: "Ahluwalia Contracts (India) Ltd", stockNameCategory: "Smallcap" },
  // ================= HEALTHCARE =================
  { symbol: "SUNPHARMA.NS", sectorId: 3, sector: "Healthcare / Pharmaceuticals", category: "Nifty50", displayName: "Sun Pharmaceutical Industries Ltd", stockNameCategory: "Largecap" },
  { symbol: "DRREDDY.NS", sectorId: 3, sector: "Healthcare / Pharmaceuticals", category: "Nifty50", displayName: "Dr. Reddy's Laboratories Ltd", stockNameCategory: "Largecap" },
  { symbol: "CIPLA.NS", sectorId: 3, sector: "Healthcare / Pharmaceuticals", category: "Nifty50", displayName: "Cipla Ltd", stockNameCategory: "Largecap" },
  { symbol: "DIVISLAB.NS", sectorId: 3, sector: "Healthcare / Pharmaceuticals", category: "Midcap", displayName: "Divi's Laboratories Ltd", stockNameCategory: "Largecap" },
  { symbol: "LUPIN.NS", sectorId: 3, sector: "Healthcare / Pharmaceuticals", category: "Midcap", displayName: "Lupin Ltd", stockNameCategory: "Largecap" },
  { symbol: "TORNTPHARM.NS", sectorId: 3, sector: "Healthcare / Pharmaceuticals", category: "Midcap", displayName: "Torrent Pharmaceuticals Ltd", stockNameCategory: "Largecap" },
  { symbol: "ALKEM.NS", sectorId: 3, sector: "Healthcare / Pharmaceuticals", category: "Midcap", displayName: "Alkem Laboratories Ltd", stockNameCategory: "Midcap" },
  { symbol: "BIOCON.NS", sectorId: 3, sector: "Healthcare / Pharmaceuticals", category: "Midcap", displayName: "Biocon Ltd", stockNameCategory: "Midcap" },
  { symbol: "AUROPHARMA.NS", sectorId: 3, sector: "Healthcare / Pharmaceuticals", category: "Midcap", displayName: "Aurobindo Pharma Ltd", stockNameCategory: "Largecap" },
  { symbol: "GLENMARK.NS", sectorId: 3, sector: "Healthcare / Pharmaceuticals", category: "Midcap", displayName: "Glenmark Pharmaceuticals Ltd", stockNameCategory: "Midcap" },
  { symbol: "ZYDUSLIFE.NS", sectorId: 3, sector: "Healthcare / Pharmaceuticals", category: "Midcap", displayName: "Zydus Lifesciences Ltd", stockNameCategory: "Largecap" },
  { symbol: "LAURUSLABS.NS", sectorId: 3, sector: "Healthcare / Pharmaceuticals", category: "Midcap", displayName: "Laurus Labs Ltd", stockNameCategory: "Midcap" },
  { symbol: "IPCALAB.NS", sectorId: 3, sector: "Healthcare / Pharmaceuticals", category: "Midcap", displayName: "IPCA Laboratories Ltd", stockNameCategory: "Midcap" },
  { symbol: "ABBOTINDIA.NS", sectorId: 3, sector: "Healthcare / Pharmaceuticals", category: "Midcap", displayName: "Abbott India Ltd", stockNameCategory: "Midcap" },
  { symbol: "PFIZER.NS", sectorId: 3, sector: "Healthcare / Pharmaceuticals", category: "Midcap", displayName: "Pfizer Ltd", stockNameCategory: "Midcap" },
  { symbol: "APOLLOHOSP.NS", sectorId: 3, sector: "Healthcare / Pharmaceuticals", category: "Midcap", displayName: "Apollo Hospitals Enterprise Ltd", stockNameCategory: "Largecap" },
  { symbol: "FORTIS.NS", sectorId: 3, sector: "Healthcare / Pharmaceuticals", category: "Midcap", displayName: "Fortis Healthcare Ltd", stockNameCategory: "Midcap" },
  { symbol: "MAXHEALTH.NS", sectorId: 3, sector: "Healthcare / Pharmaceuticals", category: "Midcap", displayName: "Max Healthcare Institute Ltd", stockNameCategory: "Midcap" },
  { symbol: "METROPOLIS.NS", sectorId: 3, sector: "Healthcare / Pharmaceuticals", category: "Midcap", displayName: "Metropolis Healthcare Ltd", stockNameCategory: "Midcap" },
  { symbol: "LALPATHLAB.NS", sectorId: 3, sector: "Healthcare / Pharmaceuticals", category: "Midcap", displayName: "Dr. Lal PathLabs Ltd", stockNameCategory: "Midcap" },
  { symbol: "ERIS.NS", sectorId: 3, sector: "Healthcare / Pharmaceuticals", category: "Midcap", displayName: "Eris Lifesciences Ltd", stockNameCategory: "Midcap" },
  { symbol: "AJANTPHARM.NS", sectorId: 3, sector: "Healthcare / Pharmaceuticals", category: "Midcap", displayName: "Ajanta Pharma Ltd", stockNameCategory: "Midcap" },
  { symbol: "GRANULES.NS", sectorId: 3, sector: "Healthcare / Pharmaceuticals", category: "Midcap", displayName: "Granules India Ltd", stockNameCategory: "Midcap" },
  { symbol: "NATCOPHARM.NS", sectorId: 3, sector: "Healthcare / Pharmaceuticals", category: "Midcap", displayName: "Natco Pharma Ltd", stockNameCategory: "Midcap" },
  { symbol: "STRIDES.NS", sectorId: 3, sector: "Healthcare / Pharmaceuticals", category: "Midcap", displayName: "Strides Pharma Science Ltd", stockNameCategory: "Midcap" },
  // ================= CONSUMER STAPLES =================
  { symbol: "HINDUNILVR.NS", sectorId: 5, sector: "Consumer Staples", category: "Nifty50", displayName: "Hindustan Unilever Ltd", stockNameCategory: "Largecap" },
  { symbol: "ITC.NS", sectorId: 5, sector: "Consumer Staples", category: "Nifty50", displayName: "ITC Ltd", stockNameCategory: "Largecap" },
  { symbol: "NESTLEIND.NS", sectorId: 5, sector: "Consumer Staples", category: "Nifty50", displayName: "Nestle India Ltd", stockNameCategory: "Largecap" },
  { symbol: "BRITANNIA.NS", sectorId: 5, sector: "Consumer Staples", category: "Nifty50", displayName: "Britannia Industries Ltd", stockNameCategory: "Largecap" },
  { symbol: "DABUR.NS", sectorId: 5, sector: "Consumer Staples", category: "Midcap", displayName: "Dabur India Ltd", stockNameCategory: "Largecap" },
  { symbol: "GODREJCP.NS", sectorId: 5, sector: "Consumer Staples", category: "Midcap", displayName: "Godrej Consumer Products Ltd", stockNameCategory: "Largecap" },
  { symbol: "MARICO.NS", sectorId: 5, sector: "Consumer Staples", category: "Midcap", displayName: "Marico Ltd", stockNameCategory: "Midcap" },
  { symbol: "COLPAL.NS", sectorId: 5, sector: "Consumer Staples", category: "Midcap", displayName: "Colgate-Palmolive (India) Ltd", stockNameCategory: "Largecap" },
  { symbol: "TATACONSUM.NS", sectorId: 5, sector: "Consumer Staples", category: "Midcap", displayName: "Tata Consumer Products Ltd", stockNameCategory: "Largecap" },
  { symbol: "UBL.NS", sectorId: 5, sector: "Consumer Staples", category: "Midcap", displayName: "United Breweries Ltd", stockNameCategory: "Midcap" },
  { symbol: "RADICO.NS", sectorId: 5, sector: "Consumer Staples", category: "Midcap", displayName: "Radico Khaitan Ltd", stockNameCategory: "Midcap" },
  { symbol: "EMAMILTD.NS", sectorId: 5, sector: "Consumer Staples", category: "Midcap", displayName: "Emami Ltd", stockNameCategory: "Midcap" },
  { symbol: "VBL.NS", sectorId: 5, sector: "Consumer Staples", category: "Midcap", displayName: "Varun Beverages Ltd", stockNameCategory: "Largecap" },
  { symbol: "PGHH.NS", sectorId: 5, sector: "Consumer Staples", category: "Midcap", displayName: "Procter & Gamble Hygiene and Health Care Ltd", stockNameCategory: "Midcap" },
  { symbol: "HATSUN.NS", sectorId: 5, sector: "Consumer Staples", category: "Midcap", displayName: "Hatsun Agro Product Ltd", stockNameCategory: "Midcap" },
  { symbol: "BAJAJCON.NS", sectorId: 5, sector: "Consumer Staples", category: "Midcap", displayName: "Bajaj Consumer Care Ltd", stockNameCategory: "Midcap" },
  { symbol: "ZYDUSWELL.NS", sectorId: 5, sector: "Consumer Staples", category: "Midcap", displayName: "Zydus Wellness Ltd", stockNameCategory: "Midcap" },
  { symbol: "TASTYBITE.NS", sectorId: 5, sector: "Consumer Staples", category: "Midcap", displayName: "Tasty Bite Eatables Ltd", stockNameCategory: "Smallcap" },
  { symbol: "BECTORFOOD.NS", sectorId: 5, sector: "Consumer Staples", category: "Midcap", displayName: "Bector Food Specialities Ltd", stockNameCategory: "Smallcap" },
  { symbol: "PRIVISCL.NS", sectorId: 5, sector: "Consumer Staples", category: "Midcap", displayName: "Privi Speciality Chemicals Ltd", stockNameCategory: "Smallcap" },
  { symbol: "KRBL.NS", sectorId: 5, sector: "Consumer Staples", category: "Midcap", displayName: "KRBL Ltd", stockNameCategory: "Midcap" },
  { symbol: "LTFOODS.NS", sectorId: 5, sector: "Consumer Staples", category: "Midcap", displayName: "LT Foods Ltd", stockNameCategory: "Midcap" },
  { symbol: "AVT.NS", sectorId: 5, sector: "Consumer Staples", category: "Midcap", displayName: "AVT Natural Products Ltd", stockNameCategory: "Smallcap" },
  { symbol: "GOKUL.NS", sectorId: 5, sector: "Consumer Staples", category: "Smallcap", displayName: "Gokul Agro Resources Ltd", stockNameCategory: "Smallcap" },
  { symbol: "HERITGFOOD.NS", sectorId: 5, sector: "Consumer Staples", category: "Smallcap", displayName: "Heritage Foods Ltd", stockNameCategory: "Smallcap" },
  // ================= COMMUNICATION =================
  { symbol: "BHARTIARTL.NS", sectorId: 11, sector: "Communication Services", category: "Nifty50", displayName: "Bharti Airtel Ltd", stockNameCategory: "Largecap" },
  { symbol: "IDEA.NS", sectorId: 11, sector: "Communication Services", category: "Midcap", displayName: "Vodafone Idea Ltd", stockNameCategory: "Largecap" },
  { symbol: "TATACOMM.NS", sectorId: 11, sector: "Communication Services", category: "Midcap", displayName: "Tata Communications Ltd", stockNameCategory: "Midcap" },
  { symbol: "ROUTE.NS", sectorId: 11, sector: "Communication Services", category: "Midcap", displayName: "Route Mobile Ltd", stockNameCategory: "Midcap" },
  { symbol: "RAILTEL.NS", sectorId: 11, sector: "Communication Services", category: "Midcap", displayName: "Railtel Corporation of India Ltd", stockNameCategory: "Midcap" },
  { symbol: "INDUSTOWER.NS", sectorId: 11, sector: "Communication Services", category: "Midcap", displayName: "Indus Towers Ltd", stockNameCategory: "Largecap" },
  { symbol: "HFCL.NS", sectorId: 11, sector: "Communication Services", category: "Midcap", displayName: "HFCL Ltd", stockNameCategory: "Midcap" },
  { symbol: "TEJASNET.NS", sectorId: 11, sector: "Communication Services", category: "Midcap", displayName: "Tejas Networks Ltd", stockNameCategory: "Midcap" },
  { symbol: "HATHWAY.NS", sectorId: 11, sector: "Communication Services", category: "Smallcap", displayName: "Hathway Cable & Datacom Ltd", stockNameCategory: "Smallcap" },
  { symbol: "DEN.NS", sectorId: 11, sector: "Communication Services", category: "Smallcap", displayName: "Den Networks Ltd", stockNameCategory: "Smallcap" },
  { symbol: "SUNTV.NS", sectorId: 11, sector: "Communication Services", category: "Midcap", displayName: "Sun TV Network Ltd", stockNameCategory: "Midcap" },
  { symbol: "ZEEL.NS", sectorId: 11, sector: "Communication Services", category: "Midcap", displayName: "Zee Entertainment Enterprises Ltd", stockNameCategory: "Midcap" },
  { symbol: "PVRINOX.NS", sectorId: 11, sector: "Communication Services", category: "Midcap", displayName: "PVR INOX Ltd", stockNameCategory: "Midcap" },
  { symbol: "INOXLEISUR.NS", sectorId: 11, sector: "Communication Services", category: "Midcap", displayName: "Inox Leisure Ltd", stockNameCategory: "Midcap" },
  { symbol: "TV18BRDCST.NS", sectorId: 11, sector: "Communication Services", category: "Midcap", displayName: "TV18 Broadcast Ltd", stockNameCategory: "Midcap" },
  { symbol: "NETWORK18.NS", sectorId: 11, sector: "Communication Services", category: "Midcap", displayName: "Network18 Media & Investments Ltd", stockNameCategory: "Midcap" },
  { symbol: "DISHTV.NS", sectorId: 11, sector: "Communication Services", category: "Smallcap", displayName: "Dish TV India Ltd", stockNameCategory: "Smallcap" },
  { symbol: "SAREGAMA.NS", sectorId: 11, sector: "Communication Services", category: "Midcap", displayName: "Saregama India Ltd", stockNameCategory: "Midcap" },
  { symbol: "GTPL.NS", sectorId: 11, sector: "Communication Services", category: "Midcap", displayName: "GTPL Hathway Ltd", stockNameCategory: "Smallcap" },
  { symbol: "NAZARA.NS", sectorId: 11, sector: "Communication Services", category: "Midcap", displayName: "Nazara Technologies Ltd", stockNameCategory: "Midcap" },
  { symbol: "ONMOBILE.NS", sectorId: 11, sector: "Communication Services", category: "Smallcap", displayName: "Onmobile Global Ltd", stockNameCategory: "Smallcap" },
  { symbol: "ZEELEARN.NS", sectorId: 11, sector: "Communication Services", category: "Smallcap", displayName: "Zee Learn Ltd", stockNameCategory: "Smallcap" },
  { symbol: "DBCORP.NS", sectorId: 11, sector: "Communication Services", category: "Smallcap", displayName: "D B Corp Ltd", stockNameCategory: "Smallcap" },
  { symbol: "JAGRAN.NS", sectorId: 11, sector: "Communication Services", category: "Smallcap", displayName: "Jagran Prakashan Ltd", stockNameCategory: "Smallcap" },
  { symbol: "HTMEDIA.NS", sectorId: 11, sector: "Communication Services", category: "Smallcap", displayName: "HT Media Ltd", stockNameCategory: "Smallcap" },
  // ================= CONSUMER DISCRETIONARY =================
  { symbol: "MARUTI.NS", sectorId: 4, sector: "Consumer Discretionary", category: "Nifty50", displayName: "Maruti Suzuki India Ltd", stockNameCategory: "Largecap" },
  { symbol: "TATAMOTORS.NS", sectorId: 4, sector: "Consumer Discretionary", category: "Nifty50", displayName: "Tata Motors Ltd", stockNameCategory: "Largecap" },
  { symbol: "M&M.NS", sectorId: 4, sector: "Consumer Discretionary", category: "Nifty50", displayName: "Mahindra & Mahindra Ltd", stockNameCategory: "Largecap" },
  { symbol: "EICHERMOT.NS", sectorId: 4, sector: "Consumer Discretionary", category: "Nifty50", displayName: "Eicher Motors Ltd", stockNameCategory: "Largecap" },
  { symbol: "BAJAJ-AUTO.NS", sectorId: 4, sector: "Consumer Discretionary", category: "Nifty50", displayName: "Bajaj Auto Ltd", stockNameCategory: "Largecap" },
  { symbol: "HEROMOTOCO.NS", sectorId: 4, sector: "Consumer Discretionary", category: "Nifty50", displayName: "Hero MotoCorp Ltd", stockNameCategory: "Largecap" },
  { symbol: "TVSMOTOR.NS", sectorId: 4, sector: "Consumer Discretionary", category: "Midcap", displayName: "TVS Motor Company Ltd", stockNameCategory: "Largecap" },
  { symbol: "TRENT.NS", sectorId: 4, sector: "Consumer Discretionary", category: "Midcap", displayName: "Trent Ltd", stockNameCategory: "Largecap" },
  { symbol: "PAGEIND.NS", sectorId: 4, sector: "Consumer Discretionary", category: "Midcap", displayName: "Page Industries Ltd", stockNameCategory: "Midcap" },
  { symbol: "DMART.NS", sectorId: 4, sector: "Consumer Discretionary", category: "Midcap", displayName: "Avenue Supermarts Ltd", stockNameCategory: "Largecap" },
  { symbol: "TITAN.NS", sectorId: 4, sector: "Consumer Discretionary", category: "Nifty50", displayName: "Titan Company Ltd", stockNameCategory: "Largecap" },
  { symbol: "ADANIENT.NS", sectorId: 4, sector: "Consumer Discretionary", category: "Nifty50", displayName: "Adani Enterprises Ltd", stockNameCategory: "Largecap" },
  { symbol: "VBL.NS", sectorId: 4, sector: "Consumer Discretionary", category: "Midcap", displayName: "Varun Beverages Ltd", stockNameCategory: "Largecap" },
  { symbol: "ZOMATO.NS", sectorId: 4, sector: "Consumer Discretionary", category: "Midcap", displayName: "Zomato Ltd", stockNameCategory: "Largecap" },
  { symbol: "NYKAA.NS", sectorId: 4, sector: "Consumer Discretionary", category: "Midcap", displayName: "FSN E-Commerce Ventures Ltd", stockNameCategory: "Midcap" },
  { symbol: "IRCTC.NS", sectorId: 4, sector: "Consumer Discretionary", category: "Midcap", displayName: "Indian Railway Catering and Tourism Corporation Ltd", stockNameCategory: "Largecap" },
  { symbol: "INDIGO.NS", sectorId: 4, sector: "Consumer Discretionary", category: "Midcap", displayName: "InterGlobe Aviation Ltd", stockNameCategory: "Largecap" },
  { symbol: "JUBLFOOD.NS", sectorId: 4, sector: "Consumer Discretionary", category: "Midcap", displayName: "Jubilant FoodWorks Ltd", stockNameCategory: "Midcap" },
  { symbol: "DEVYANI.NS", sectorId: 4, sector: "Consumer Discretionary", category: "Midcap", displayName: "Devyani International Ltd", stockNameCategory: "Midcap" },
  { symbol: "WESTLIFE.NS", sectorId: 4, sector: "Consumer Discretionary", category: "Midcap", displayName: "Westlife FoodWorld Ltd", stockNameCategory: "Midcap" },
  { symbol: "RELAXO.NS", sectorId: 4, sector: "Consumer Discretionary", category: "Midcap", displayName: "Relaxo Footwears Ltd", stockNameCategory: "Midcap" },
  { symbol: "BATAINDIA.NS", sectorId: 4, sector: "Consumer Discretionary", category: "Midcap", displayName: "Bata India Ltd", stockNameCategory: "Midcap" },
  { symbol: "KALYANKJIL.NS", sectorId: 4, sector: "Consumer Discretionary", category: "Midcap", displayName: "Kalyan Jewellers India Ltd", stockNameCategory: "Midcap" },
  { symbol: "METROBRAND.NS", sectorId: 4, sector: "Consumer Discretionary", category: "Midcap", displayName: "Metro Brands Ltd", stockNameCategory: "Midcap" },
  { symbol: "VMART.NS", sectorId: 4, sector: "Consumer Discretionary", category: "Midcap", displayName: "V-Mart Retail Ltd", stockNameCategory: "Midcap" },
  // ================= INDUSTRIALS =================
  { symbol: "LT.NS", sectorId: 6, sector: "Industrials", category: "Nifty50", displayName: "Larsen & Toubro Ltd", stockNameCategory: "Largecap" },
  { symbol: "SIEMENS.NS", sectorId: 6, sector: "Industrials", category: "Midcap", displayName: "Siemens Ltd", stockNameCategory: "Largecap" },
  { symbol: "ABB.NS", sectorId: 6, sector: "Industrials", category: "Midcap", displayName: "ABB India Ltd", stockNameCategory: "Largecap" },
  { symbol: "BHEL.NS", sectorId: 6, sector: "Industrials", category: "Midcap", displayName: "Bharat Heavy Electricals Ltd", stockNameCategory: "Midcap" },
  { symbol: "HAL.NS", sectorId: 6, sector: "Industrials", category: "Midcap", displayName: "Hindustan Aeronautics Ltd", stockNameCategory: "Largecap" },
  { symbol: "BEL.NS", sectorId: 6, sector: "Industrials", category: "Midcap", displayName: "Bharat Electronics Ltd", stockNameCategory: "Largecap" },
  { symbol: "CGPOWER.NS", sectorId: 6, sector: "Industrials", category: "Midcap", displayName: "CG Power and Industrial Solutions Ltd", stockNameCategory: "Midcap" },
  { symbol: "THERMAX.NS", sectorId: 6, sector: "Industrials", category: "Midcap", displayName: "Thermax Ltd", stockNameCategory: "Midcap" },
  { symbol: "CUMMINSIND.NS", sectorId: 6, sector: "Industrials", category: "Midcap", displayName: "Cummins India Ltd", stockNameCategory: "Midcap" },
  { symbol: "SKFINDIA.NS", sectorId: 6, sector: "Industrials", category: "Midcap", displayName: "SKF India Ltd", stockNameCategory: "Midcap" },
  { symbol: "KEI.NS", sectorId: 6, sector: "Industrials", category: "Midcap", displayName: "KEI Industries Ltd", stockNameCategory: "Midcap" },
  { symbol: "POLYCAB.NS", sectorId: 6, sector: "Industrials", category: "Midcap", displayName: "Polycab India Ltd", stockNameCategory: "Largecap" },
  { symbol: "AIAENG.NS", sectorId: 6, sector: "Industrials", category: "Midcap", displayName: "AIA Engineering Ltd", stockNameCategory: "Midcap" },
  { symbol: "ESCORTS.NS", sectorId: 6, sector: "Industrials", category: "Midcap", displayName: "Escorts Kubota Ltd", stockNameCategory: "Midcap" },
  { symbol: "KIRLOSENG.NS", sectorId: 6, sector: "Industrials", category: "Midcap", displayName: "Kirloskar Oil Engines Ltd", stockNameCategory: "Midcap" },
  { symbol: "VOLTAS.NS", sectorId: 6, sector: "Industrials", category: "Midcap", displayName: "Voltas Ltd", stockNameCategory: "Midcap" },
  { symbol: "BLUESTARCO.NS", sectorId: 6, sector: "Industrials", category: "Midcap", displayName: "Blue Star Ltd", stockNameCategory: "Midcap" },
  { symbol: "TIMKEN.NS", sectorId: 6, sector: "Industrials", category: "Midcap", displayName: "Timken India Ltd", stockNameCategory: "Midcap" },
  { symbol: "SCHAEFFLER.NS", sectorId: 6, sector: "Industrials", category: "Midcap", displayName: "Schaeffler India Ltd", stockNameCategory: "Midcap" },
  { symbol: "ELGIEQUIP.NS", sectorId: 6, sector: "Industrials", category: "Midcap", displayName: "Elgi Equipments Ltd", stockNameCategory: "Midcap" },
  { symbol: "KSB.NS", sectorId: 6, sector: "Industrials", category: "Midcap", displayName: "KSB Ltd", stockNameCategory: "Midcap" },
  { symbol: "GRINDWELL.NS", sectorId: 6, sector: "Industrials", category: "Midcap", displayName: "Grindwell Norton Ltd", stockNameCategory: "Midcap" },
  { symbol: "FINCABLES.NS", sectorId: 6, sector: "Industrials", category: "Midcap", displayName: "Finolex Cables Ltd", stockNameCategory: "Midcap" },
  { symbol: "RRKABEL.NS", sectorId: 6, sector: "Industrials", category: "Midcap", displayName: "RR Kabel Ltd", stockNameCategory: "Midcap" },
  { symbol: "HAVELLS.NS", sectorId: 6, sector: "Industrials", category: "Midcap", displayName: "Havells India Ltd", stockNameCategory: "Largecap" },
  // ================= UTILITIES =================
  { symbol: "NTPC.NS", sectorId: 9, sector: "Utilities", category: "Nifty50", displayName: "NTPC Ltd", stockNameCategory: "Largecap" },
  { symbol: "POWERGRID.NS", sectorId: 9, sector: "Utilities", category: "Nifty50", displayName: "Power Grid Corporation of India Ltd", stockNameCategory: "Largecap" },
  { symbol: "NHPC.NS", sectorId: 9, sector: "Utilities", category: "Midcap", displayName: "NHPC Ltd", stockNameCategory: "Midcap" },
  { symbol: "SJVN.NS", sectorId: 9, sector: "Utilities", category: "Midcap", displayName: "SJVN Ltd", stockNameCategory: "Midcap" },
  { symbol: "ADANIPOWER.NS", sectorId: 9, sector: "Utilities", category: "Midcap", displayName: "Adani Power Ltd", stockNameCategory: "Largecap" },
  { symbol: "TATAPOWER.NS", sectorId: 9, sector: "Utilities", category: "Midcap", displayName: "Tata Power Company Ltd", stockNameCategory: "Largecap" },
  { symbol: "TORNTPOWER.NS", sectorId: 9, sector: "Utilities", category: "Midcap", displayName: "Torrent Power Ltd", stockNameCategory: "Midcap" },
  { symbol: "CESC.NS", sectorId: 9, sector: "Utilities", category: "Midcap", displayName: "CESC Ltd", stockNameCategory: "Midcap" },
  { symbol: "JSWENERGY.NS", sectorId: 9, sector: "Utilities", category: "Midcap", displayName: "JSW Energy Ltd", stockNameCategory: "Midcap" },
  { symbol: "NLCINDIA.NS", sectorId: 9, sector: "Utilities", category: "Midcap", displayName: "NLC India Ltd", stockNameCategory: "Midcap" },
  { symbol: "GUJGASLTD.NS", sectorId: 9, sector: "Utilities", category: "Midcap", displayName: "Gujarat Gas Ltd", stockNameCategory: "Midcap" },
  { symbol: "IGL.NS", sectorId: 9, sector: "Utilities", category: "Midcap", displayName: "Indraprastha Gas Ltd", stockNameCategory: "Midcap" },
  { symbol: "MGL.NS", sectorId: 9, sector: "Utilities", category: "Midcap", displayName: "Mahanagar Gas Ltd", stockNameCategory: "Midcap" },
  { symbol: "ATGL.NS", sectorId: 9, sector: "Utilities", category: "Midcap", displayName: "Adani Total Gas Ltd", stockNameCategory: "Midcap" },
  { symbol: "ADANIGREEN.NS", sectorId: 9, sector: "Utilities", category: "Midcap", displayName: "Adani Green Energy Ltd", stockNameCategory: "Largecap" },
  { symbol: "RELINFRA.NS", sectorId: 9, sector: "Utilities", category: "Midcap", displayName: "Reliance Infrastructure Ltd", stockNameCategory: "Smallcap" },
  { symbol: "RTNPOWER.NS", sectorId: 9, sector: "Utilities", category: "Smallcap", displayName: "RattanIndia Power Ltd", stockNameCategory: "Smallcap" },
  { symbol: "JPPOWER.NS", sectorId: 9, sector: "Utilities", category: "Smallcap", displayName: "Jaiprakash Power Ventures Ltd", stockNameCategory: "Smallcap" },
  { symbol: "ORIENTELEC.NS", sectorId: 9, sector: "Utilities", category: "Midcap", displayName: "Orient Electric Ltd", stockNameCategory: "Midcap" },
  { symbol: "INOXWIND.NS", sectorId: 9, sector: "Utilities", category: "Midcap", displayName: "Inox Wind Ltd", stockNameCategory: "Smallcap" },
  { symbol: "SUZLON.NS", sectorId: 9, sector: "Utilities", category: "Midcap", displayName: "Suzlon Energy Ltd", stockNameCategory: "Midcap" },
  { symbol: "STERPOWER.NS", sectorId: 9, sector: "Utilities", category: "Smallcap", displayName: "Sterling and Wilson Renewable Energy Ltd", stockNameCategory: "Smallcap" },
  { symbol: "GREENPOWER.NS", sectorId: 9, sector: "Utilities", category: "Smallcap", displayName: "Green Power Ltd", stockNameCategory: "Smallcap" },
  { symbol: "WAAREEENER.NS", sectorId: 9, sector: "Utilities", category: "Midcap", displayName: "Waaree Energies Ltd", stockNameCategory: "Midcap" },
  { symbol: "BOROSILREN.NS", sectorId: 9, sector: "Utilities", category: "Midcap", displayName: "Borosil Renewables Ltd", stockNameCategory: "Smallcap" },
];