export const STOCKS = [
  // ================= ENERGY =================
  { symbol: "RELIANCE.NS", sectorId: 7, sector: "Energy", category: "Nifty50", displayName: "Reliance Industries", stockNameCategory: "Largecap" },
  { symbol: "ONGC.NS", sectorId: 7, sector: "Energy", category: "Nifty50", displayName: "Oil and Natural Gas Corporation", stockNameCategory: "Largecap" },
  { symbol: "IOC.NS", sectorId: 7, sector: "Energy", category: "Midcap", displayName: "Indian Oil Corporation", stockNameCategory: "Largecap" },
  { symbol: "BPCL.NS", sectorId: 7, sector: "Energy", category: "Midcap", displayName: "Bharat Petroleum Corporation", stockNameCategory: "Largecap" },
  { symbol: "HINDPETRO.NS", sectorId: 7, sector: "Energy", category: "Midcap", displayName: "Hindustan Petroleum Corporation", stockNameCategory: "Largecap" },
  { symbol: "GAIL.NS", sectorId: 7, sector: "Energy", category: "Midcap", displayName: "GAIL (India)", stockNameCategory: "Largecap" },
  { symbol: "OIL.NS", sectorId: 7, sector: "Energy", category: "Midcap", displayName: "Oil India", stockNameCategory: "Midcap" },
  { symbol: "PETRONET.NS", sectorId: 7, sector: "Energy", category: "Midcap", displayName: "Petronet LNG", stockNameCategory: "Midcap" },
  { symbol: "IGL.NS", sectorId: 7, sector: "Energy", category: "Midcap", displayName: "Indraprastha Gas", stockNameCategory: "Midcap" },
  { symbol: "MGL.NS", sectorId: 7, sector: "Energy", category: "Midcap", displayName: "Mahanagar Gas", stockNameCategory: "Midcap" },
  { symbol: "GSPL.NS", sectorId: 7, sector: "Energy", category: "Midcap", displayName: "Gujarat State Petronet", stockNameCategory: "Midcap" },
  { symbol: "GUJGASLTD.NS", sectorId: 7, sector: "Energy", category: "Midcap", displayName: "Gujarat Gas", stockNameCategory: "Midcap" },
  { symbol: "ATGL.NS", sectorId: 7, sector: "Energy", category: "Midcap", displayName: "Adani Total Gas", stockNameCategory: "Midcap" },
  { symbol: "ADANIGREEN.NS", sectorId: 7, sector: "Energy", category: "Midcap", displayName: "Adani Green Energy", stockNameCategory: "Largecap" },
  { symbol: "ADANIPOWER.NS", sectorId: 7, sector: "Energy", category: "Midcap", displayName: "Adani Power", stockNameCategory: "Largecap" },
  { symbol: "NTPC.NS", sectorId: 7, sector: "Energy", category: "Nifty50", displayName: "NTPC", stockNameCategory: "Largecap" },
  { symbol: "NHPC.NS", sectorId: 7, sector: "Energy", category: "Midcap", displayName: "NHPC", stockNameCategory: "Midcap" },
  { symbol: "SJVN.NS", sectorId: 7, sector: "Energy", category: "Midcap", displayName: "SJVN", stockNameCategory: "Midcap" },
  { symbol: "TORNTPOWER.NS", sectorId: 7, sector: "Energy", category: "Midcap", displayName: "Torrent Power", stockNameCategory: "Midcap" },
  { symbol: "TATAPOWER.NS", sectorId: 7, sector: "Energy", category: "Midcap", displayName: "Tata Power Company", stockNameCategory: "Largecap" },
  { symbol: "JSWENERGY.NS", sectorId: 7, sector: "Energy", category: "Midcap", displayName: "JSW Energy", stockNameCategory: "Midcap" },
  { symbol: "CESC.NS", sectorId: 7, sector: "Energy", category: "Midcap", displayName: "CESC", stockNameCategory: "Midcap" },
  { symbol: "NLCINDIA.NS", sectorId: 7, sector: "Energy", category: "Midcap", displayName: "NLC India", stockNameCategory: "Midcap" },
  { symbol: "POWERGRID.NS", sectorId: 7, sector: "Energy", category: "Nifty50", displayName: "Power Grid Corporation of India", stockNameCategory: "Largecap" },
  { symbol: "ADANIENSOL.NS", sectorId: 7, sector: "Energy", category: "Midcap", displayName: "Adani Energy Solutions", stockNameCategory: "Midcap" },
  // ================= MATERIALS =================
  { symbol: "ULTRACEMCO.NS", sectorId: 8, sector: "Materials", category: "Midcap", displayName: "UltraTech Cement", stockNameCategory: "Largecap" },
  { symbol: "GRASIM.NS", sectorId: 8, sector: "Materials", category: "Midcap", displayName: "Grasim Industries", stockNameCategory: "Largecap" },
  { symbol: "TATASTEEL.NS", sectorId: 8, sector: "Materials", category: "Nifty50", displayName: "Tata Steel", stockNameCategory: "Largecap" },
  { symbol: "JSWSTEEL.NS", sectorId: 8, sector: "Materials", category: "Midcap", displayName: "JSW Steel", stockNameCategory: "Largecap" },
  { symbol: "HINDALCO.NS", sectorId: 8, sector: "Materials", category: "Nifty50", displayName: "Hindalco Industries", stockNameCategory: "Largecap" },
  { symbol: "VEDL.NS", sectorId: 8, sector: "Materials", category: "Midcap", displayName: "Vedanta", stockNameCategory: "Largecap" },
  { symbol: "SAIL.NS", sectorId: 8, sector: "Materials", category: "Midcap", displayName: "Steel Authority of India", stockNameCategory: "Midcap" },
  { symbol: "JINDALSTEL.NS", sectorId: 8, sector: "Materials", category: "Midcap", displayName: "Jindal Steel & Power", stockNameCategory: "Midcap" },
  { symbol: "NMDC.NS", sectorId: 8, sector: "Materials", category: "Midcap", displayName: "NMDC", stockNameCategory: "Midcap" },
  { symbol: "AMBUJACEM.NS", sectorId: 8, sector: "Materials", category: "Midcap", displayName: "Ambuja Cements", stockNameCategory: "Largecap" },
  { symbol: "ACC.NS", sectorId: 8, sector: "Materials", category: "Midcap", displayName: "ACC", stockNameCategory: "Midcap" },
  { symbol: "DALBHARAT.NS", sectorId: 8, sector: "Materials", category: "Midcap", displayName: "Dalmia Bharat", stockNameCategory: "Midcap" },
  { symbol: "RAMCOCEM.NS", sectorId: 8, sector: "Materials", category: "Midcap", displayName: "The Ramco Cements", stockNameCategory: "Midcap" },
  { symbol: "APLAPOLLO.NS", sectorId: 8, sector: "Materials", category: "Midcap", displayName: "Apollo Pipes", stockNameCategory: "Midcap" },
  { symbol: "JSPL.NS", sectorId: 8, sector: "Materials", category: "Midcap", displayName: "Jindal Steel & Power", stockNameCategory: "Midcap" },
  { symbol: "HINDZINC.NS", sectorId: 8, sector: "Materials", category: "Midcap", displayName: "Hindustan Zinc", stockNameCategory: "Largecap" },
  { symbol: "NATIONALUM.NS", sectorId: 8, sector: "Materials", category: "Midcap", displayName: "National Aluminium Company", stockNameCategory: "Midcap" },
  { symbol: "MOIL.NS", sectorId: 8, sector: "Materials", category: "Midcap", displayName: "MOIL", stockNameCategory: "Midcap" },
  { symbol: "RATNAMANI.NS", sectorId: 8, sector: "Materials", category: "Midcap", displayName: "Ratnamani Metals & Tubes", stockNameCategory: "Midcap" },
  { symbol: "SUPREMEIND.NS", sectorId: 8, sector: "Materials", category: "Midcap", displayName: "Supreme Industries", stockNameCategory: "Midcap" },
  { symbol: "ASTRAL.NS", sectorId: 8, sector: "Materials", category: "Midcap", displayName: "Astral", stockNameCategory: "Midcap" },
  { symbol: "KANSAINER.NS", sectorId: 8, sector: "Materials", category: "Midcap", displayName: "Kansai Nerolac Paints", stockNameCategory: "Midcap" },
  { symbol: "BERGEPAINT.NS", sectorId: 8, sector: "Materials", category: "Midcap", displayName: "Berger Paints India", stockNameCategory: "Midcap" },
  { symbol: "PIDILITIND.NS", sectorId: 8, sector: "Materials", category: "Midcap", displayName: "Pidilite Industries", stockNameCategory: "Largecap" },
  { symbol: "DEEPAKNTR.NS", sectorId: 8, sector: "Materials", category: "Midcap", displayName: "Deepak Nitrite", stockNameCategory: "Midcap" },
  // ================= FINANCIALS =================
  { symbol: "HDFCBANK.NS", sectorId: 2, sector: "Financials", category: "Nifty50", displayName: "HDFC Bank", stockNameCategory: "Largecap" },
  { symbol: "ICICIBANK.NS", sectorId: 2, sector: "Financials", category: "Nifty50", displayName: "ICICI Bank", stockNameCategory: "Largecap" },
  { symbol: "SBIN.NS", sectorId: 2, sector: "Financials", category: "Nifty50", displayName: "State Bank of India", stockNameCategory: "Largecap" },
  { symbol: "KOTAKBANK.NS", sectorId: 2, sector: "Financials", category: "Nifty50", displayName: "Kotak Mahindra Bank", stockNameCategory: "Largecap" },
  { symbol: "AXISBANK.NS", sectorId: 2, sector: "Financials", category: "Nifty50", displayName: "Axis Bank", stockNameCategory: "Largecap" },
  { symbol: "BAJFINANCE.NS", sectorId: 2, sector: "Financials", category: "Nifty50", displayName: "Bajaj Finance", stockNameCategory: "Largecap" },
  { symbol: "BAJAJFINSV.NS", sectorId: 2, sector: "Financials", category: "Nifty50", displayName: "Bajaj Finserv", stockNameCategory: "Largecap" },
  { symbol: "HDFCLIFE.NS", sectorId: 2, sector: "Financials", category: "Midcap", displayName: "HDFC Life Insurance Company", stockNameCategory: "Largecap" },
  { symbol: "SBILIFE.NS", sectorId: 2, sector: "Financials", category: "Midcap", displayName: "SBI Life Insurance Company", stockNameCategory: "Largecap" },
  { symbol: "ICICIPRULI.NS", sectorId: 2, sector: "Financials", category: "Midcap", displayName: "ICICI Prudential Life Insurance Company", stockNameCategory: "Largecap" },
  { symbol: "ICICIGI.NS", sectorId: 2, sector: "Financials", category: "Midcap", displayName: "ICICI Lombard General Insurance Company", stockNameCategory: "Midcap" },
  { symbol: "PFC.NS", sectorId: 2, sector: "Financials", category: "Midcap", displayName: "Power Finance Corporation", stockNameCategory: "Largecap" },
  { symbol: "RECLTD.NS", sectorId: 2, sector: "Financials", category: "Midcap", displayName: "REC", stockNameCategory: "Largecap" },
  { symbol: "CHOLAFIN.NS", sectorId: 2, sector: "Financials", category: "Midcap", displayName: "Cholamandalam Investment and Finance Company", stockNameCategory: "Midcap" },
  { symbol: "MUTHOOTFIN.NS", sectorId: 2, sector: "Financials", category: "Midcap", displayName: "Muthoot Finance", stockNameCategory: "Midcap" },
  { symbol: "LICI.NS", sectorId: 2, sector: "Financials", category: "Midcap", displayName: "Life Insurance Corporation of India", stockNameCategory: "Largecap" },
  { symbol: "HDFCAMC.NS", sectorId: 2, sector: "Financials", category: "Midcap", displayName: "HDFC Asset Management Company", stockNameCategory: "Midcap" },
  { symbol: "IDFCFIRSTB.NS", sectorId: 2, sector: "Financials", category: "Midcap", displayName: "IDFC First Bank", stockNameCategory: "Midcap" },
  { symbol: "FEDERALBNK.NS", sectorId: 2, sector: "Financials", category: "Midcap", displayName: "Federal Bank", stockNameCategory: "Midcap" },
  { symbol: "BANDHANBNK.NS", sectorId: 2, sector: "Financials", category: "Midcap", displayName: "Bandhan Bank", stockNameCategory: "Midcap" },
  { symbol: "INDUSINDBK.NS", sectorId: 2, sector: "Financials", category: "Midcap", displayName: "IndusInd Bank", stockNameCategory: "Largecap" },
  { symbol: "CANBK.NS", sectorId: 2, sector: "Financials", category: "Midcap", displayName: "Canara Bank", stockNameCategory: "Midcap" },
  { symbol: "BANKBARODA.NS", sectorId: 2, sector: "Financials", category: "Midcap", displayName: "Bank of Baroda", stockNameCategory: "Largecap" },
  { symbol: "UNIONBANK.NS", sectorId: 2, sector: "Financials", category: "Midcap", displayName: "Union Bank of India", stockNameCategory: "Midcap" },
  { symbol: "AUBANK.NS", sectorId: 2, sector: "Financials", category: "Midcap", displayName: "AU Small Finance Bank", stockNameCategory: "Midcap" },
  // ================= IT =================
  { symbol: "TCS.NS", sectorId: 1, sector: "Information Technology", category: "Nifty50", displayName: "Tata Consultancy Services", stockNameCategory: "Largecap" },
  { symbol: "INFY.NS", sectorId: 1, sector: "Information Technology", category: "Nifty50", displayName: "Infosys", stockNameCategory: "Largecap" },
  { symbol: "HCLTECH.NS", sectorId: 1, sector: "Information Technology", category: "Nifty50", displayName: "HCL Technologies", stockNameCategory: "Largecap" },
  { symbol: "WIPRO.NS", sectorId: 1, sector: "Information Technology", category: "Nifty50", displayName: "Wipro", stockNameCategory: "Largecap" },
  { symbol: "LTIM.NS", sectorId: 1, sector: "Information Technology", category: "Midcap", displayName: "LTIMindtree", stockNameCategory: "Largecap" },
  { symbol: "TECHM.NS", sectorId: 1, sector: "Information Technology", category: "Midcap", displayName: "Tech Mahindra", stockNameCategory: "Largecap" },
  { symbol: "PERSISTENT.NS", sectorId: 1, sector: "Information Technology", category: "Midcap", displayName: "Persistent Systems", stockNameCategory: "Midcap" },
  { symbol: "MPHASIS.NS", sectorId: 1, sector: "Information Technology", category: "Midcap", displayName: "Mphasis", stockNameCategory: "Midcap" },
  { symbol: "COFORGE.NS", sectorId: 1, sector: "Information Technology", category: "Midcap", displayName: "Coforge", stockNameCategory: "Midcap" },
  { symbol: "LTTS.NS", sectorId: 1, sector: "Information Technology", category: "Midcap", displayName: "L&T Technology Services", stockNameCategory: "Midcap" },
  { symbol: "TATAELXSI.NS", sectorId: 1, sector: "Information Technology", category: "Midcap", displayName: "Tata Elxsi", stockNameCategory: "Midcap" },
  { symbol: "KPITTECH.NS", sectorId: 1, sector: "Information Technology", category: "Midcap", displayName: "KPIT Technologies", stockNameCategory: "Midcap" },
  { symbol: "SONATSOFTW.NS", sectorId: 1, sector: "Information Technology", category: "Midcap", displayName: "Sonata Software", stockNameCategory: "Midcap" },
  { symbol: "ZENSARTECH.NS", sectorId: 1, sector: "Information Technology", category: "Midcap", displayName: "Zensar Technologies", stockNameCategory: "Midcap" },
  { symbol: "CYIENT.NS", sectorId: 1, sector: "Information Technology", category: "Midcap", displayName: "Cyient", stockNameCategory: "Midcap" },
  { symbol: "BIRLASOFT.NS", sectorId: 1, sector: "Information Technology", category: "Midcap", displayName: "Birlasoft", stockNameCategory: "Midcap" },
  { symbol: "HAPPSTMNDS.NS", sectorId: 1, sector: "Information Technology", category: "Midcap", displayName: "Happiest Minds Technologies", stockNameCategory: "Midcap" },
  { symbol: "NEWGEN.NS", sectorId: 1, sector: "Information Technology", category: "Midcap", displayName: "Newgen Software Technologies", stockNameCategory: "Midcap" },
  { symbol: "RAMCOSYS.NS", sectorId: 1, sector: "Information Technology", category: "Midcap", displayName: "Ramco Systems", stockNameCategory: "Smallcap" },
  { symbol: "OFSS.NS", sectorId: 1, sector: "Information Technology", category: "Midcap", displayName: "Oracle Financial Services Software", stockNameCategory: "Midcap" },
  { symbol: "INTELLECT.NS", sectorId: 1, sector: "Information Technology", category: "Midcap", displayName: "Intellect Design Arena", stockNameCategory: "Midcap" },
  { symbol: "ROUTE.NS", sectorId: 1, sector: "Information Technology", category: "Midcap", displayName: "Route Mobile", stockNameCategory: "Midcap" },
  { symbol: "LATENTVIEW.NS", sectorId: 1, sector: "Information Technology", category: "Midcap", displayName: "Latent View Analytics", stockNameCategory: "Midcap" },
  { symbol: "TANLA.NS", sectorId: 1, sector: "Information Technology", category: "Midcap", displayName: "Tanla Platforms", stockNameCategory: "Midcap" },
  { symbol: "AFFLE.NS", sectorId: 1, sector: "Information Technology", category: "Midcap", displayName: "Affle (India)", stockNameCategory: "Midcap" },
  // ================= REAL ESTATE =================
  { symbol: "DLF.NS", sectorId: 10, sector: "Real Estate", category: "Midcap", displayName: "DLF", stockNameCategory: "Largecap" },
  { symbol: "GODREJPROP.NS", sectorId: 10, sector: "Real Estate", category: "Midcap", displayName: "Godrej Properties", stockNameCategory: "Midcap" },
  { symbol: "OBEROIRLTY.NS", sectorId: 10, sector: "Real Estate", category: "Midcap", displayName: "Oberoi Realty", stockNameCategory: "Midcap" },
  { symbol: "PHOENIXLTD.NS", sectorId: 10, sector: "Real Estate", category: "Midcap", displayName: "Phoenix Mills", stockNameCategory: "Midcap" },
  { symbol: "BRIGADE.NS", sectorId: 10, sector: "Real Estate", category: "Midcap", displayName: "Brigade Enterprises", stockNameCategory: "Midcap" },
  { symbol: "SOBHA.NS", sectorId: 10, sector: "Real Estate", category: "Midcap", displayName: "Sobha", stockNameCategory: "Midcap" },
  { symbol: "PRESTIGE.NS", sectorId: 10, sector: "Real Estate", category: "Midcap", displayName: "Prestige Estates Projects", stockNameCategory: "Midcap" },
  { symbol: "LODHA.NS", sectorId: 10, sector: "Real Estate", category: "Midcap", displayName: "Macrotech Developers", stockNameCategory: "Largecap" },
  { symbol: "MAHLIFE.NS", sectorId: 10, sector: "Real Estate", category: "Midcap", displayName: "Mahindra Lifespace Developers", stockNameCategory: "Midcap" },
  { symbol: "SUNTECK.NS", sectorId: 10, sector: "Real Estate", category: "Midcap", displayName: "Sunteck Realty", stockNameCategory: "Midcap" },
  { symbol: "KOLTEPATIL.NS", sectorId: 10, sector: "Real Estate", category: "Midcap", displayName: "Kolte-Patil Developers", stockNameCategory: "Midcap" },
  { symbol: "PURVA.NS", sectorId: 10, sector: "Real Estate", category: "Midcap", displayName: "Puravankara", stockNameCategory: "Smallcap" },
  { symbol: "ANANTRAJ.NS", sectorId: 10, sector: "Real Estate", category: "Midcap", displayName: "Anant Raj", stockNameCategory: "Midcap" },
  { symbol: "IBREALEST.NS", sectorId: 10, sector: "Real Estate", category: "Midcap", displayName: "Indiabulls Real Estate", stockNameCategory: "Smallcap" },
  { symbol: "HEMIPROP.NS", sectorId: 10, sector: "Real Estate", category: "Smallcap", displayName: "Hemisphere Properties India", stockNameCategory: "Smallcap" },
  { symbol: "ASHIANA.NS", sectorId: 10, sector: "Real Estate", category: "Midcap", displayName: "Ashiana Housing", stockNameCategory: "Smallcap" },
  { symbol: "DBREALTY.NS", sectorId: 10, sector: "Real Estate", category: "Smallcap", displayName: "D B Realty", stockNameCategory: "Smallcap" },
  { symbol: "OMAXE.NS", sectorId: 10, sector: "Real Estate", category: "Smallcap", displayName: "Omaxe", stockNameCategory: "Smallcap" },
  { symbol: "UNITECH.NS", sectorId: 10, sector: "Real Estate", category: "Smallcap", displayName: "Unitech", stockNameCategory: "Penny" },
  { symbol: "VIPULLTD.NS", sectorId: 10, sector: "Real Estate", category: "Smallcap", displayName: "Vipul", stockNameCategory: "Penny" },
  { symbol: "ARVSMART.NS", sectorId: 10, sector: "Real Estate", category: "Smallcap", displayName: "Arvind SmartSpaces", stockNameCategory: "Smallcap" },
  { symbol: "NILKAMAL.NS", sectorId: 10, sector: "Real Estate", category: "Midcap", displayName: "Nilkamal", stockNameCategory: "Midcap" },
  { symbol: "PSPPROJECT.NS", sectorId: 10, sector: "Real Estate", category: "Midcap", displayName: "PSP Projects", stockNameCategory: "Smallcap" },
  { symbol: "CAPACITE.NS", sectorId: 10, sector: "Real Estate", category: "Midcap", displayName: "Capacite Infraprojects", stockNameCategory: "Smallcap" },
  { symbol: "AHLEAST.NS", sectorId: 10, sector: "Real Estate", category: "Smallcap", displayName: "Ahluwalia Contracts (India)", stockNameCategory: "Smallcap" },
  // ================= HEALTHCARE =================
  { symbol: "SUNPHARMA.NS", sectorId: 3, sector: "Healthcare / Pharmaceuticals", category: "Nifty50", displayName: "Sun Pharmaceutical Industries", stockNameCategory: "Largecap" },
  { symbol: "DRREDDY.NS", sectorId: 3, sector: "Healthcare / Pharmaceuticals", category: "Nifty50", displayName: "Dr. Reddy's Laboratories", stockNameCategory: "Largecap" },
  { symbol: "CIPLA.NS", sectorId: 3, sector: "Healthcare / Pharmaceuticals", category: "Nifty50", displayName: "Cipla", stockNameCategory: "Largecap" },
  { symbol: "DIVISLAB.NS", sectorId: 3, sector: "Healthcare / Pharmaceuticals", category: "Midcap", displayName: "Divi's Laboratories", stockNameCategory: "Largecap" },
  { symbol: "LUPIN.NS", sectorId: 3, sector: "Healthcare / Pharmaceuticals", category: "Midcap", displayName: "Lupin", stockNameCategory: "Largecap" },
  { symbol: "TORNTPHARM.NS", sectorId: 3, sector: "Healthcare / Pharmaceuticals", category: "Midcap", displayName: "Torrent Pharmaceuticals", stockNameCategory: "Largecap" },
  { symbol: "ALKEM.NS", sectorId: 3, sector: "Healthcare / Pharmaceuticals", category: "Midcap", displayName: "Alkem Laboratories", stockNameCategory: "Midcap" },
  { symbol: "BIOCON.NS", sectorId: 3, sector: "Healthcare / Pharmaceuticals", category: "Midcap", displayName: "Biocon", stockNameCategory: "Midcap" },
  { symbol: "AUROPHARMA.NS", sectorId: 3, sector: "Healthcare / Pharmaceuticals", category: "Midcap", displayName: "Aurobindo Pharma", stockNameCategory: "Largecap" },
  { symbol: "GLENMARK.NS", sectorId: 3, sector: "Healthcare / Pharmaceuticals", category: "Midcap", displayName: "Glenmark Pharmaceuticals", stockNameCategory: "Midcap" },
  { symbol: "ZYDUSLIFE.NS", sectorId: 3, sector: "Healthcare / Pharmaceuticals", category: "Midcap", displayName: "Zydus Lifesciences", stockNameCategory: "Largecap" },
  { symbol: "LAURUSLABS.NS", sectorId: 3, sector: "Healthcare / Pharmaceuticals", category: "Midcap", displayName: "Laurus Labs", stockNameCategory: "Midcap" },
  { symbol: "IPCALAB.NS", sectorId: 3, sector: "Healthcare / Pharmaceuticals", category: "Midcap", displayName: "IPCA Laboratories", stockNameCategory: "Midcap" },
  { symbol: "ABBOTINDIA.NS", sectorId: 3, sector: "Healthcare / Pharmaceuticals", category: "Midcap", displayName: "Abbott India", stockNameCategory: "Midcap" },
  { symbol: "PFIZER.NS", sectorId: 3, sector: "Healthcare / Pharmaceuticals", category: "Midcap", displayName: "Pfizer", stockNameCategory: "Midcap" },
  { symbol: "APOLLOHOSP.NS", sectorId: 3, sector: "Healthcare / Pharmaceuticals", category: "Midcap", displayName: "Apollo Hospitals Enterprise", stockNameCategory: "Largecap" },
  { symbol: "FORTIS.NS", sectorId: 3, sector: "Healthcare / Pharmaceuticals", category: "Midcap", displayName: "Fortis Healthcare", stockNameCategory: "Midcap" },
  { symbol: "MAXHEALTH.NS", sectorId: 3, sector: "Healthcare / Pharmaceuticals", category: "Midcap", displayName: "Max Healthcare Institute", stockNameCategory: "Midcap" },
  { symbol: "METROPOLIS.NS", sectorId: 3, sector: "Healthcare / Pharmaceuticals", category: "Midcap", displayName: "Metropolis Healthcare", stockNameCategory: "Midcap" },
  { symbol: "LALPATHLAB.NS", sectorId: 3, sector: "Healthcare / Pharmaceuticals", category: "Midcap", displayName: "Dr. Lal PathLabs", stockNameCategory: "Midcap" },
  { symbol: "ERIS.NS", sectorId: 3, sector: "Healthcare / Pharmaceuticals", category: "Midcap", displayName: "Eris Lifesciences", stockNameCategory: "Midcap" },
  { symbol: "AJANTPHARM.NS", sectorId: 3, sector: "Healthcare / Pharmaceuticals", category: "Midcap", displayName: "Ajanta Pharma", stockNameCategory: "Midcap" },
  { symbol: "GRANULES.NS", sectorId: 3, sector: "Healthcare / Pharmaceuticals", category: "Midcap", displayName: "Granules India", stockNameCategory: "Midcap" },
  { symbol: "NATCOPHARM.NS", sectorId: 3, sector: "Healthcare / Pharmaceuticals", category: "Midcap", displayName: "Natco Pharma", stockNameCategory: "Midcap" },
  { symbol: "STRIDES.NS", sectorId: 3, sector: "Healthcare / Pharmaceuticals", category: "Midcap", displayName: "Strides Pharma Science", stockNameCategory: "Midcap" },
  // ================= CONSUMER STAPLES =================
  { symbol: "HINDUNILVR.NS", sectorId: 5, sector: "Consumer Staples", category: "Nifty50", displayName: "Hindustan Unilever", stockNameCategory: "Largecap" },
  { symbol: "ITC.NS", sectorId: 5, sector: "Consumer Staples", category: "Nifty50", displayName: "ITC", stockNameCategory: "Largecap" },
  { symbol: "NESTLEIND.NS", sectorId: 5, sector: "Consumer Staples", category: "Nifty50", displayName: "Nestle India", stockNameCategory: "Largecap" },
  { symbol: "BRITANNIA.NS", sectorId: 5, sector: "Consumer Staples", category: "Nifty50", displayName: "Britannia Industries", stockNameCategory: "Largecap" },
  { symbol: "DABUR.NS", sectorId: 5, sector: "Consumer Staples", category: "Midcap", displayName: "Dabur India", stockNameCategory: "Largecap" },
  { symbol: "GODREJCP.NS", sectorId: 5, sector: "Consumer Staples", category: "Midcap", displayName: "Godrej Consumer Products", stockNameCategory: "Largecap" },
  { symbol: "MARICO.NS", sectorId: 5, sector: "Consumer Staples", category: "Midcap", displayName: "Marico", stockNameCategory: "Midcap" },
  { symbol: "COLPAL.NS", sectorId: 5, sector: "Consumer Staples", category: "Midcap", displayName: "Colgate-Palmolive (India)", stockNameCategory: "Largecap" },
  { symbol: "TATACONSUM.NS", sectorId: 5, sector: "Consumer Staples", category: "Midcap", displayName: "Tata Consumer Products", stockNameCategory: "Largecap" },
  { symbol: "UBL.NS", sectorId: 5, sector: "Consumer Staples", category: "Midcap", displayName: "United Breweries", stockNameCategory: "Midcap" },
  { symbol: "RADICO.NS", sectorId: 5, sector: "Consumer Staples", category: "Midcap", displayName: "Radico Khaitan", stockNameCategory: "Midcap" },
  { symbol: "EMAMILTD.NS", sectorId: 5, sector: "Consumer Staples", category: "Midcap", displayName: "Emami", stockNameCategory: "Midcap" },
  { symbol: "VBL.NS", sectorId: 5, sector: "Consumer Staples", category: "Midcap", displayName: "Varun Beverages", stockNameCategory: "Largecap" },
  { symbol: "PGHH.NS", sectorId: 5, sector: "Consumer Staples", category: "Midcap", displayName: "Procter & Gamble Hygiene and Health Care", stockNameCategory: "Midcap" },
  { symbol: "HATSUN.NS", sectorId: 5, sector: "Consumer Staples", category: "Midcap", displayName: "Hatsun Agro Product", stockNameCategory: "Midcap" },
  { symbol: "BAJAJCON.NS", sectorId: 5, sector: "Consumer Staples", category: "Midcap", displayName: "Bajaj Consumer Care", stockNameCategory: "Midcap" },
  { symbol: "ZYDUSWELL.NS", sectorId: 5, sector: "Consumer Staples", category: "Midcap", displayName: "Zydus Wellness", stockNameCategory: "Midcap" },
  { symbol: "TASTYBITE.NS", sectorId: 5, sector: "Consumer Staples", category: "Midcap", displayName: "Tasty Bite Eatables", stockNameCategory: "Smallcap" },
  { symbol: "BECTORFOOD.NS", sectorId: 5, sector: "Consumer Staples", category: "Midcap", displayName: "Bector Food Specialities", stockNameCategory: "Smallcap" },
  { symbol: "PRIVISCL.NS", sectorId: 5, sector: "Consumer Staples", category: "Midcap", displayName: "Privi Speciality Chemicals", stockNameCategory: "Smallcap" },
  { symbol: "KRBL.NS", sectorId: 5, sector: "Consumer Staples", category: "Midcap", displayName: "KRBL", stockNameCategory: "Midcap" },
  { symbol: "LTFOODS.NS", sectorId: 5, sector: "Consumer Staples", category: "Midcap", displayName: "LT Foods", stockNameCategory: "Midcap" },
  { symbol: "AVT.NS", sectorId: 5, sector: "Consumer Staples", category: "Midcap", displayName: "AVT Natural Products", stockNameCategory: "Smallcap" },
  { symbol: "GOKUL.NS", sectorId: 5, sector: "Consumer Staples", category: "Smallcap", displayName: "Gokul Agro Resources", stockNameCategory: "Smallcap" },
  { symbol: "HERITGFOOD.NS", sectorId: 5, sector: "Consumer Staples", category: "Smallcap", displayName: "Heritage Foods", stockNameCategory: "Smallcap" },
  // ================= COMMUNICATION =================
  { symbol: "BHARTIARTL.NS", sectorId: 11, sector: "Communication Services", category: "Nifty50", displayName: "Bharti Airtel", stockNameCategory: "Largecap" },
  { symbol: "IDEA.NS", sectorId: 11, sector: "Communication Services", category: "Midcap", displayName: "Vodafone Idea", stockNameCategory: "Largecap" },
  { symbol: "TATACOMM.NS", sectorId: 11, sector: "Communication Services", category: "Midcap", displayName: "Tata Communications", stockNameCategory: "Midcap" },
  { symbol: "ROUTE.NS", sectorId: 11, sector: "Communication Services", category: "Midcap", displayName: "Route Mobile", stockNameCategory: "Midcap" },
  { symbol: "RAILTEL.NS", sectorId: 11, sector: "Communication Services", category: "Midcap", displayName: "Railtel Corporation of India", stockNameCategory: "Midcap" },
  { symbol: "INDUSTOWER.NS", sectorId: 11, sector: "Communication Services", category: "Midcap", displayName: "Indus Towers", stockNameCategory: "Largecap" },
  { symbol: "HFCL.NS", sectorId: 11, sector: "Communication Services", category: "Midcap", displayName: "HFCL", stockNameCategory: "Midcap" },
  { symbol: "TEJASNET.NS", sectorId: 11, sector: "Communication Services", category: "Midcap", displayName: "Tejas Networks", stockNameCategory: "Midcap" },
  { symbol: "HATHWAY.NS", sectorId: 11, sector: "Communication Services", category: "Smallcap", displayName: "Hathway Cable & Datacom", stockNameCategory: "Smallcap" },
  { symbol: "DEN.NS", sectorId: 11, sector: "Communication Services", category: "Smallcap", displayName: "Den Networks", stockNameCategory: "Smallcap" },
  { symbol: "SUNTV.NS", sectorId: 11, sector: "Communication Services", category: "Midcap", displayName: "Sun TV Network", stockNameCategory: "Midcap" },
  { symbol: "ZEEL.NS", sectorId: 11, sector: "Communication Services", category: "Midcap", displayName: "Zee Entertainment Enterprises", stockNameCategory: "Midcap" },
  { symbol: "PVRINOX.NS", sectorId: 11, sector: "Communication Services", category: "Midcap", displayName: "PVR INOX", stockNameCategory: "Midcap" },
  { symbol: "INOXLEISUR.NS", sectorId: 11, sector: "Communication Services", category: "Midcap", displayName: "Inox Leisure", stockNameCategory: "Midcap" },
  { symbol: "TV18BRDCST.NS", sectorId: 11, sector: "Communication Services", category: "Midcap", displayName: "TV18 Broadcast", stockNameCategory: "Midcap" },
  { symbol: "NETWORK18.NS", sectorId: 11, sector: "Communication Services", category: "Midcap", displayName: "Network18 Media & Investments", stockNameCategory: "Midcap" },
  { symbol: "DISHTV.NS", sectorId: 11, sector: "Communication Services", category: "Smallcap", displayName: "Dish TV India", stockNameCategory: "Smallcap" },
  { symbol: "SAREGAMA.NS", sectorId: 11, sector: "Communication Services", category: "Midcap", displayName: "Saregama India", stockNameCategory: "Midcap" },
  { symbol: "GTPL.NS", sectorId: 11, sector: "Communication Services", category: "Midcap", displayName: "GTPL Hathway", stockNameCategory: "Smallcap" },
  { symbol: "NAZARA.NS", sectorId: 11, sector: "Communication Services", category: "Midcap", displayName: "Nazara Technologies", stockNameCategory: "Midcap" },
  { symbol: "ONMOBILE.NS", sectorId: 11, sector: "Communication Services", category: "Smallcap", displayName: "Onmobile Global", stockNameCategory: "Smallcap" },
  { symbol: "ZEELEARN.NS", sectorId: 11, sector: "Communication Services", category: "Smallcap", displayName: "Zee Learn", stockNameCategory: "Smallcap" },
  { symbol: "DBCORP.NS", sectorId: 11, sector: "Communication Services", category: "Smallcap", displayName: "D B Corp", stockNameCategory: "Smallcap" },
  { symbol: "JAGRAN.NS", sectorId: 11, sector: "Communication Services", category: "Smallcap", displayName: "Jagran Prakashan", stockNameCategory: "Smallcap" },
  { symbol: "HTMEDIA.NS", sectorId: 11, sector: "Communication Services", category: "Smallcap", displayName: "HT Media", stockNameCategory: "Smallcap" },
  // ================= CONSUMER DISCRETIONARY =================
  { symbol: "MARUTI.NS", sectorId: 4, sector: "Consumer Discretionary", category: "Nifty50", displayName: "Maruti Suzuki India", stockNameCategory: "Largecap" },
  { symbol: "TATAMOTORS.NS", sectorId: 4, sector: "Consumer Discretionary", category: "Nifty50", displayName: "Tata Motors", stockNameCategory: "Largecap" },
  { symbol: "M&M.NS", sectorId: 4, sector: "Consumer Discretionary", category: "Nifty50", displayName: "Mahindra & Mahindra", stockNameCategory: "Largecap" },
  { symbol: "EICHERMOT.NS", sectorId: 4, sector: "Consumer Discretionary", category: "Nifty50", displayName: "Eicher Motors", stockNameCategory: "Largecap" },
  { symbol: "BAJAJ-AUTO.NS", sectorId: 4, sector: "Consumer Discretionary", category: "Nifty50", displayName: "Bajaj Auto", stockNameCategory: "Largecap" },
  { symbol: "HEROMOTOCO.NS", sectorId: 4, sector: "Consumer Discretionary", category: "Nifty50", displayName: "Hero MotoCorp", stockNameCategory: "Largecap" },
  { symbol: "TVSMOTOR.NS", sectorId: 4, sector: "Consumer Discretionary", category: "Midcap", displayName: "TVS Motor Company", stockNameCategory: "Largecap" },
  { symbol: "TRENT.NS", sectorId: 4, sector: "Consumer Discretionary", category: "Midcap", displayName: "Trent", stockNameCategory: "Largecap" },
  { symbol: "PAGEIND.NS", sectorId: 4, sector: "Consumer Discretionary", category: "Midcap", displayName: "Page Industries", stockNameCategory: "Midcap" },
  { symbol: "DMART.NS", sectorId: 4, sector: "Consumer Discretionary", category: "Midcap", displayName: "Avenue Supermarts", stockNameCategory: "Largecap" },
  { symbol: "TITAN.NS", sectorId: 4, sector: "Consumer Discretionary", category: "Nifty50", displayName: "Titan Company", stockNameCategory: "Largecap" },
  { symbol: "ADANIENT.NS", sectorId: 4, sector: "Consumer Discretionary", category: "Nifty50", displayName: "Adani Enterprises", stockNameCategory: "Largecap" },
  { symbol: "VBL.NS", sectorId: 4, sector: "Consumer Discretionary", category: "Midcap", displayName: "Varun Beverages", stockNameCategory: "Largecap" },
  { symbol: "ZOMATO.NS", sectorId: 4, sector: "Consumer Discretionary", category: "Midcap", displayName: "Zomato", stockNameCategory: "Largecap" },
  { symbol: "NYKAA.NS", sectorId: 4, sector: "Consumer Discretionary", category: "Midcap", displayName: "FSN E-Commerce Ventures", stockNameCategory: "Midcap" },
  { symbol: "IRCTC.NS", sectorId: 4, sector: "Consumer Discretionary", category: "Midcap", displayName: "Indian Railway Catering and Tourism Corporation", stockNameCategory: "Largecap" },
  { symbol: "INDIGO.NS", sectorId: 4, sector: "Consumer Discretionary", category: "Midcap", displayName: "InterGlobe Aviation", stockNameCategory: "Largecap" },
  { symbol: "JUBLFOOD.NS", sectorId: 4, sector: "Consumer Discretionary", category: "Midcap", displayName: "Jubilant FoodWorks", stockNameCategory: "Midcap" },
  { symbol: "DEVYANI.NS", sectorId: 4, sector: "Consumer Discretionary", category: "Midcap", displayName: "Devyani International", stockNameCategory: "Midcap" },
  { symbol: "WESTLIFE.NS", sectorId: 4, sector: "Consumer Discretionary", category: "Midcap", displayName: "Westlife FoodWorld", stockNameCategory: "Midcap" },
  { symbol: "RELAXO.NS", sectorId: 4, sector: "Consumer Discretionary", category: "Midcap", displayName: "Relaxo Footwears", stockNameCategory: "Midcap" },
  { symbol: "BATAINDIA.NS", sectorId: 4, sector: "Consumer Discretionary", category: "Midcap", displayName: "Bata India", stockNameCategory: "Midcap" },
  { symbol: "KALYANKJIL.NS", sectorId: 4, sector: "Consumer Discretionary", category: "Midcap", displayName: "Kalyan Jewellers India", stockNameCategory: "Midcap" },
  { symbol: "METROBRAND.NS", sectorId: 4, sector: "Consumer Discretionary", category: "Midcap", displayName: "Metro Brands", stockNameCategory: "Midcap" },
  { symbol: "VMART.NS", sectorId: 4, sector: "Consumer Discretionary", category: "Midcap", displayName: "V-Mart Retail", stockNameCategory: "Midcap" },
  // ================= INDUSTRIALS =================
  { symbol: "LT.NS", sectorId: 6, sector: "Industrials", category: "Nifty50", displayName: "Larsen & Toubro", stockNameCategory: "Largecap" },
  { symbol: "SIEMENS.NS", sectorId: 6, sector: "Industrials", category: "Midcap", displayName: "Siemens", stockNameCategory: "Largecap" },
  { symbol: "ABB.NS", sectorId: 6, sector: "Industrials", category: "Midcap", displayName: "ABB India", stockNameCategory: "Largecap" },
  { symbol: "BHEL.NS", sectorId: 6, sector: "Industrials", category: "Midcap", displayName: "Bharat Heavy Electricals", stockNameCategory: "Midcap" },
  { symbol: "HAL.NS", sectorId: 6, sector: "Industrials", category: "Midcap", displayName: "Hindustan Aeronautics", stockNameCategory: "Largecap" },
  { symbol: "BEL.NS", sectorId: 6, sector: "Industrials", category: "Midcap", displayName: "Bharat Electronics", stockNameCategory: "Largecap" },
  { symbol: "CGPOWER.NS", sectorId: 6, sector: "Industrials", category: "Midcap", displayName: "CG Power and Industrial Solutions", stockNameCategory: "Midcap" },
  { symbol: "THERMAX.NS", sectorId: 6, sector: "Industrials", category: "Midcap", displayName: "Thermax", stockNameCategory: "Midcap" },
  { symbol: "CUMMINSIND.NS", sectorId: 6, sector: "Industrials", category: "Midcap", displayName: "Cummins India", stockNameCategory: "Midcap" },
  { symbol: "SKFINDIA.NS", sectorId: 6, sector: "Industrials", category: "Midcap", displayName: "SKF India", stockNameCategory: "Midcap" },
  { symbol: "KEI.NS", sectorId: 6, sector: "Industrials", category: "Midcap", displayName: "KEI Industries", stockNameCategory: "Midcap" },
  { symbol: "POLYCAB.NS", sectorId: 6, sector: "Industrials", category: "Midcap", displayName: "Polycab India", stockNameCategory: "Largecap" },
  { symbol: "AIAENG.NS", sectorId: 6, sector: "Industrials", category: "Midcap", displayName: "AIA Engineering", stockNameCategory: "Midcap" },
  { symbol: "ESCORTS.NS", sectorId: 6, sector: "Industrials", category: "Midcap", displayName: "Escorts Kubota", stockNameCategory: "Midcap" },
  { symbol: "KIRLOSENG.NS", sectorId: 6, sector: "Industrials", category: "Midcap", displayName: "Kirloskar Oil Engines", stockNameCategory: "Midcap" },
  { symbol: "VOLTAS.NS", sectorId: 6, sector: "Industrials", category: "Midcap", displayName: "Voltas", stockNameCategory: "Midcap" },
  { symbol: "BLUESTARCO.NS", sectorId: 6, sector: "Industrials", category: "Midcap", displayName: "Blue Star", stockNameCategory: "Midcap" },
  { symbol: "TIMKEN.NS", sectorId: 6, sector: "Industrials", category: "Midcap", displayName: "Timken India", stockNameCategory: "Midcap" },
  { symbol: "SCHAEFFLER.NS", sectorId: 6, sector: "Industrials", category: "Midcap", displayName: "Schaeffler India", stockNameCategory: "Midcap" },
  { symbol: "ELGIEQUIP.NS", sectorId: 6, sector: "Industrials", category: "Midcap", displayName: "Elgi Equipments", stockNameCategory: "Midcap" },
  { symbol: "KSB.NS", sectorId: 6, sector: "Industrials", category: "Midcap", displayName: "KSB", stockNameCategory: "Midcap" },
  { symbol: "GRINDWELL.NS", sectorId: 6, sector: "Industrials", category: "Midcap", displayName: "Grindwell Norton", stockNameCategory: "Midcap" },
  { symbol: "FINCABLES.NS", sectorId: 6, sector: "Industrials", category: "Midcap", displayName: "Finolex Cables", stockNameCategory: "Midcap" },
  { symbol: "RRKABEL.NS", sectorId: 6, sector: "Industrials", category: "Midcap", displayName: "RR Kabel", stockNameCategory: "Midcap" },
  { symbol: "HAVELLS.NS", sectorId: 6, sector: "Industrials", category: "Midcap", displayName: "Havells India", stockNameCategory: "Largecap" },
  // ================= UTILITIES =================
  { symbol: "NTPC.NS", sectorId: 9, sector: "Utilities", category: "Nifty50", displayName: "NTPC", stockNameCategory: "Largecap" },
  { symbol: "POWERGRID.NS", sectorId: 9, sector: "Utilities", category: "Nifty50", displayName: "Power Grid Corporation of India", stockNameCategory: "Largecap" },
  { symbol: "NHPC.NS", sectorId: 9, sector: "Utilities", category: "Midcap", displayName: "NHPC", stockNameCategory: "Midcap" },
  { symbol: "SJVN.NS", sectorId: 9, sector: "Utilities", category: "Midcap", displayName: "SJVN", stockNameCategory: "Midcap" },
  { symbol: "ADANIPOWER.NS", sectorId: 9, sector: "Utilities", category: "Midcap", displayName: "Adani Power", stockNameCategory: "Largecap" },
  { symbol: "TATAPOWER.NS", sectorId: 9, sector: "Utilities", category: "Midcap", displayName: "Tata Power Company", stockNameCategory: "Largecap" },
  { symbol: "TORNTPOWER.NS", sectorId: 9, sector: "Utilities", category: "Midcap", displayName: "Torrent Power", stockNameCategory: "Midcap" },
  { symbol: "CESC.NS", sectorId: 9, sector: "Utilities", category: "Midcap", displayName: "CESC", stockNameCategory: "Midcap" },
  { symbol: "JSWENERGY.NS", sectorId: 9, sector: "Utilities", category: "Midcap", displayName: "JSW Energy", stockNameCategory: "Midcap" },
  { symbol: "NLCINDIA.NS", sectorId: 9, sector: "Utilities", category: "Midcap", displayName: "NLC India", stockNameCategory: "Midcap" },
  { symbol: "GUJGASLTD.NS", sectorId: 9, sector: "Utilities", category: "Midcap", displayName: "Gujarat Gas", stockNameCategory: "Midcap" },
  { symbol: "IGL.NS", sectorId: 9, sector: "Utilities", category: "Midcap", displayName: "Indraprastha Gas", stockNameCategory: "Midcap" },
  { symbol: "MGL.NS", sectorId: 9, sector: "Utilities", category: "Midcap", displayName: "Mahanagar Gas", stockNameCategory: "Midcap" },
  { symbol: "ATGL.NS", sectorId: 9, sector: "Utilities", category: "Midcap", displayName: "Adani Total Gas", stockNameCategory: "Midcap" },
  { symbol: "ADANIGREEN.NS", sectorId: 9, sector: "Utilities", category: "Midcap", displayName: "Adani Green Energy", stockNameCategory: "Largecap" },
  { symbol: "RELINFRA.NS", sectorId: 9, sector: "Utilities", category: "Midcap", displayName: "Reliance Infrastructure", stockNameCategory: "Smallcap" },
  { symbol: "RTNPOWER.NS", sectorId: 9, sector: "Utilities", category: "Smallcap", displayName: "RattanIndia Power", stockNameCategory: "Smallcap" },
  { symbol: "JPPOWER.NS", sectorId: 9, sector: "Utilities", category: "Smallcap", displayName: "Jaiprakash Power Ventures", stockNameCategory: "Smallcap" },
  { symbol: "ORIENTELEC.NS", sectorId: 9, sector: "Utilities", category: "Midcap", displayName: "Orient Electric", stockNameCategory: "Midcap" },
  { symbol: "INOXWIND.NS", sectorId: 9, sector: "Utilities", category: "Midcap", displayName: "Inox Wind", stockNameCategory: "Smallcap" },
  { symbol: "SUZLON.NS", sectorId: 9, sector: "Utilities", category: "Midcap", displayName: "Suzlon Energy", stockNameCategory: "Midcap" },
  { symbol: "STERPOWER.NS", sectorId: 9, sector: "Utilities", category: "Smallcap", displayName: "Sterling and Wilson Renewable Energy", stockNameCategory: "Smallcap" },
  { symbol: "GREENPOWER.NS", sectorId: 9, sector: "Utilities", category: "Smallcap", displayName: "Green Power", stockNameCategory: "Smallcap" },
  { symbol: "WAAREEENER.NS", sectorId: 9, sector: "Utilities", category: "Midcap", displayName: "Waaree Energies", stockNameCategory: "Midcap" },
  { symbol: "BOROSILREN.NS", sectorId: 9, sector: "Utilities", category: "Midcap", displayName: "Borosil Renewables", stockNameCategory: "Smallcap" },
];