service: SP-Node-Lambda-Functions
provider:
  name: aws
  region: ap-south-1
  runtime: nodejs20.x
  timeout: 30
  environment:
    #APIS
    JWT_SECRET: "iamworkinginheliosassoftwareengineer"
    CountryTable: Country
    TokenHistoryTable: TokenHistory
    CategoryTable: StockCategory
    StockTermTable: StockTerms
    UserCFTable: UserCF
    NewsTable: NewsRawData
    FilteredNews: FilteredNews
    SectorDetailsTable: SectorDetails
    UrlExtractionTable: UrlExtraction
    DeepStockAnalysis: DeepStocksAnalysis
    SelectedStocksTable: SelectedStocks
    PlacedStocksTable: PlacedStocks
    #ANGLE_ONE_CONFIGURATIONS
    Smart_API_KEY : "uVNH5DtC"
    Smart_API_JWT_TOKEN: "eyJhbGciOiJIUzUxMiJ9.eyJ1c2VybmFtZSI6IkFBQ0c2NjE4MjciLCJyb2xlcyI6MCwidXNlcnR5cGUiOiJVU0VSIiwidG9rZW4iOiJleUpoYkdjaU9pSlNVekkxTmlJc0luUjVjQ0k2SWtwWFZDSjkuZXlKMWMyVnlYM1I1Y0dVaU9pSmpiR2xsYm5RaUxDSjBiMnRsYmw5MGVYQmxJam9pZEhKaFpHVmZZV05qWlhOelgzUnZhMlZ1SWl3aVoyMWZhV1FpT2pNc0luTnZkWEpqWlNJNklqTWlMQ0prWlhacFkyVmZhV1FpT2lJd05UWmhaRGs1WWkxaE1qWTFMVE5tTkdVdFlXSmlOaTA1T0RabFltSTNOalk0Wm1JaUxDSnJhV1FpT2lKMGNtRmtaVjlyWlhsZmRqSWlMQ0p2Ylc1bGJXRnVZV2RsY21sa0lqb3pMQ0p3Y205a2RXTjBjeUk2ZXlKa1pXMWhkQ0k2ZXlKemRHRjBkWE1pT2lKaFkzUnBkbVVpZlN3aWJXWWlPbnNpYzNSaGRIVnpJam9pWVdOMGFYWmxJbjE5TENKcGMzTWlPaUowY21Ga1pWOXNiMmRwYmw5elpYSjJhV05sSWl3aWMzVmlJam9pUVVGRFJ6WTJNVGd5TnlJc0ltVjRjQ0k2TVRjM05qYzBNakV5TkN3aWJtSm1Jam94TnpjMk5qVTFOVFEwTENKcFlYUWlPakUzTnpZMk5UVTFORFFzSW1wMGFTSTZJalUyTXpFM1pUZGhMV1JsTTJZdE5EVTNOeTFoTmpFd0xUZGpaVEZtTURVeU5HTmpNQ0lzSWxSdmEyVnVJam9pSW4wLmN4V2Jmbnhxa0ZaVGJkUTRUdzljYjlfaU93RDNpcWJON2RHUlJnMXAyVlpNNzlMbHJjOWlMLTJPM21FSUNjWHYwUC1tTVdWd1k1SkEtV092OUJPbVB0RHlNQTlXV0VkRzI4OWFEdnVldnd0X1NaVUNhRlZXcU9MdGgtUDhiSE9vemNBX1pkSVpRb0FlZnhRaFdWV0dJSmZtOHVOZVpySkZCWHgwclFIUjdoOCIsIkFQSS1LRVkiOiJ1Vk5INUR0QyIsIlgtT0xELUFQSS1LRVkiOmZhbHNlLCJpYXQiOjE3NzY2NTU3MjQsImV4cCI6MTc3NjcwOTgwMH0.y_0o31J2TCZKmtt_SyBEWSg9jQ-wrAR3rusSB347Kybde30Vxlb2StSM8DVhTOYnlz7r7tljdQfhvlxSmCIzFw"
    Smart_API_SECRET: "625a12f7-a8de-4c19-9382-abfcb8be0bdf"
    Smart_API_PublicIP: "45.114.212.194"
    Smart_API_LocalIP: "127.0.0.1"
    Capital: 10000,
    Risk_Per_Trade: 0.4,
    #Lambdas

  iam:
    role:
      statements:
        - Effect: Allow
          Action:
            - dynamodb:Scan
            - dynamodb:GetItem
            - dynamodb:Query
            - dynamodb:PutItem
            - dynamodb:UpdateItem
          Resource:
            - arn:aws:dynamodb:ap-south-1:332717545786:table/*
        - Effect: Allow
          Action:
            - lambda:InvokeFunction
          Resource: "*"
        - Effect: Allow
          Action:
            - aws-marketplace:ViewSubscriptions
            - aws-marketplace:Subscribe
          Resource: "*"
        - Effect: Allow
          Action:
            - bedrock:InvokeModel
          Resource: "*"
        - Effect: Allow
          Action:
            - logs:CreateLogGroup
            - logs:CreateLogStream
            - logs:PutLogEvents
          Resource: "*"

plugins:
  - serverless-offline

functions:
  getCountries:
    handler: handlers/country.get
    events:
      - http:
          path: countries
          method: get

  postToken:
    handler: Common/auth.tokengeneration
    events:
      - http:
          path: tokengeneration
          method: put

  getStockTerms:
    handler: handlers/stockTerm.get
    events:
      - http:
          path: stockterms
          method: get

  getStockCategory:
    handler: handlers/stockCategory.get
    events:
      - http:
          path: stockcategory
          method: get

  userFlow:
    handler: handlers/userFlow.get
    events:
      - http:
          path: userflow
          method: put
 
  getCountry:
    handler: handlers/country.getCountry
    events:
      - http:
          path: country
          method: get

  showTermAnalysis:
    handler: handlers/getAnalysis.showTermAnalysis
    events:
      - http:
          path: showtermanalysis
          method: get

  showCategoryAnalysis:
    handler: handlers/getAnalysis.showCategoryAnalysis
    events:
      - http:
          path: showcategoryanalysis
          method: get

  showSectorAnalysis:
    handler: handlers/getAnalysis.showSectorAnalysis
    events:
      - http:
          path: showsectoranalysis
          method: get

  showStockAnalysis:
    handler: handlers/getAnalysis.showStockAnalysis
    events:
      - http:
          path: showstockanalysis
          method: get
  
  showNiftyAnalysis:
    handler: handlers/getAnalysis.showNiftyAnalysis
    events:
      - http:
          path: showniftyanlysis
          method: get

############# Externl Calls ##############

  callMain:
    handler: External/main.main
    timeout: 600
    description: "get news & execute all prompts"
    events:
      - http:
          path: executeMarketAnalysis
          method: get

  executeDeepStockAnalysis:
    handler: External/stocksDeepAnalysis.get
    timeout: 600
    description: "start the analysis over stocks insights"
    events:
      - http:
          path: deepStockAnalysis
          method: get

  tempTesting:
    handler: External/stocksAnalysis.getStockAnalysis
    timeout: 600
    description: "temporary testing lambda for stock analysis logic"
    events:
      - http:
          path: tempTesting
          method: post

############# Externl Calls ##############
  getNews:
    handler: External/newsAnalysis.get
    timeout: 600
    description: "Fetches news data for a given country and date range"    

  getmarketAnalysis:
    handler: External/marketAnalysis.getAnalysis
    timeout: 300
    description: "Term, category and sector analysis"

  getstocksAnalysis:
    handler: External/stocksAnalysis.getStockAnalysis
    timeout: 300
    description: "Generate the stocks from insights."

  geturlExtraction:
    handler: External/urlExtraction.urlExtraction
    timeout: 300
    description: "Fetch the URLs from the raw data."
      
############## Cron Jobs ##############
  cronJob:
    handler: External/cron.cron
    timeout: 300
    description: "Cron job to update stock data"

  BcronJob:
    handler: External/Bcron.Bcron
    timeout: 300
    description: "Cron job to update stock data for bearish sniper"